### ISSUE TITLE
Can not connect to Transmission RPC

### ISSUE THREAD

**Issue by vongola12324** [jesec/flood#102]
Type: Bug Report

- [x] Try to follow the update procedure described in the README and try again before opening this issue.
- [x] Please check the [F.A.Q.](https://github.com/Flood-UI/flood/wiki/F.A.Q.).
- [x] Please check the [Troubleshooting](https://github.com/Flood-UI/flood/wiki/Troubleshooting) wiki section.

## Your Environment
- Version used:
  - Version (stable release) `4.0.2`
  - Commit ID (development release) `20172fe2a407240d0d0c122544673152e18cbede`
- Environment name and version:
  - Node.js version: `v12.19.0`
  - npm version: `6.14.8`
  - Web browser: `Brave version 1.16.76 (Chromium: 86.0.4240.198)`
- Operating System and version: `Debian 10`
- Transmission version:  `Transmission 2.94 (d8e60ee44f)`

## Summary
I have installed transmission instead of rtorrent as the backend to download torrent.
But I found that I can not connect to the transmission RPC backend. (
I have checked the setting of transmission, and I can connect to the web UI provided by `transmission-daemon` package.
When I look at the list of requests in Transmission's Web UI, I see that the first RPC request for Transmission will be `409 Conflict` because the request does not have an `X-Transmission-Session-Id` header. The second RPC request will automatically send the `X-Transmission-Session-Id` header from the previous response, and we can get the response from RPC correctly. 
![2020-11-22 00 46 08](https://user-images.githubusercontent.com/5770715/99882541-29830d80-2c5c-11eb-9d63-84e2631d0e98.png)
![2020-11-22 00 47 06](https://user-images.githubusercontent.com/5770715/99882554-47e90900-2c5c-11eb-9c27-2faf95d83818.png)

## Expected Behavior
It should not display any error.

## Current Behavior
We will get an error in browser console:
![2020-11-22 00 33 56](https://user-images.githubusercontent.com/5770715/99882341-a57c5600-2c5a-11eb-8b28-bc4a3a86862e.png)

Also the dev console will show an error like this:
```
Trace: Error:
    at /home/rtorrent/flood/server/services/Transmission/clientRequestManager.ts:107:17
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at /home/rtorrent/flood/server/util/ajaxUtil.ts:7:17
    at /home/rtorrent/flood/server/routes/api/client.ts:47:19
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
GET /api/client/settings 500 3.422 ms - 2
```

## Possible Solution
In [Transmission/clientRequestManager.ts#L106](https://github.com/jesec/flood/blob/master/server/services/Transmission/clientRequestManager.ts#L106), it seems that flood is trying to get session data, but fails because it encounters the 409 error mentioned above.
According to the request list of Transmission Web UI, the first RPC request may fail because of no `X-Transmission-Session-Id` header in request, and it will resend the request with the `X-Transmission-Session-Id` header received from previous response.
First RPC request: 
![2020-11-22 00 53 43](https://user-images.githubusercontent.com/5770715/99882686-4f5ce200-2c5d-11eb-937e-d38d5dd6b471.png)
Second RPC request:
![2020-11-22 00 54 16](https://user-images.githubusercontent.com/5770715/99882687-4ff57880-2c5d-11eb-84ad-9ed4922252fd.png)

Perhaps we should check if the response is `409 Conflict`, and if so, take the `X-Transmission-Session-Id` header from the response, attach it to the header and resend the request again.

## Steps to Reproduce
As mentioned above, there are no additional setup steps (either for Flood or Transmission).

## Context
N/A

**Comment by jesec** [comment]
Flood does properly handle that.

https://github.com/jesec/flood/blob/9cb821bb3072f7cda48f8d3910c4344b1aee8469/server/services/Transmission/clientRequestManager.ts#L38-L40

All critical Flood APIs are tested against the RPC interface of a [real Transmission instance](https://github.com/jesec/flood/blob/master/server/.jest/transmission.setup.js).

https://github.com/jesec/flood/blob/master/server/.jest/transmission.setup.js

Results of 4.1.2: ALL PASSED. (https://github.com/jesec/flood/runs/1432231658?check_suite_focus=true)

Thus, it is highly improbable that the issue is related to Flood. Some suggestions:

- Check supplied Transmission RPC interface URL. Flood expects something like `http://host:port/transmission/rpc`
- Check Transmission configuration. 
- Update Transmission to latest version (3.00 is the tested version).

**Comment by vongola12324** [comment]
Oh, my bad. I didn't notice that it had been handled.

And also, I have found out the problem.
I seems that I can not use `127.0.0.1:9091` as RPC URL, even if flood and transmission are both on same server. That's strange...
But it work correctly with LAN IP (`192.168.*.*`) now.

Sorry for report this. I'm going to close this issue.

**Comment by jesec** [comment]
It is probably related to listening address of Transmission. For security reasons, Transmission will refuse to accept the requests if they don't come from the defined addresses.

**Comment by vongola12324** [comment]
Ohhhh!!! I mis-configured the `rpc-bind-address` setting. 😭 
My goodness, this problem has been bothering me for almost a week, and now it's finally solved.

Thank you.

**Comment by angristan** [comment]
Here's a config that worked for me:

```json
    "rpc-authentication-required": true,
    "rpc-bind-address": "127.0.0.1",
    "rpc-enabled": true,
    "rpc-host-whitelist": "",
    "rpc-host-whitelist-enabled": false,
    "rpc-password": "<_myhash_>",
    "rpc-port": 9091,
    "rpc-url": "/transmission/",
    "rpc-username": "transmission",
    "rpc-whitelist": "127.0.0.1",
    "rpc-whitelist-enabled": true,
```

And RPC URL set to `http://127.0.0.1:9091/transmission/rpc` on Flood.
