### ISSUE TITLE
API is not functionnal with auth=none

### ISSUE THREAD

**Issue by ThinkChaos** [jesec/flood#103]
Type: Bug Report

- [x] Try to follow the update procedure described in the README and try again before opening this issue.
- [x] Please check the [F.A.Q.](https://github.com/Flood-UI/flood/wiki/F.A.Q.).
- [x] Please check the [Troubleshooting](https://github.com/Flood-UI/flood/wiki/Troubleshooting) wiki section.

(The issue template still links to Flood-UI's wiki -- you probably want to change that)

## Your Environment

- Version used: 4.1.2

## Summary

I disabled auth, but can't use the API. I expected the API to by accessible just like the rest.

## Possible Solution

Skip passport binding for `/api` if `auth=none`: [server/routes/api/index.ts](https://github.com/jesec/flood/blob/3fb51e28b029b3c9d6d4bbe6a00f205e02fc197f/server/routes/api/index.ts#L24)

## Steps to Reproduce

```bash
$ # Launch flood somehow
$ flood --auth=none &

$ # Try to access the API
$ curl localhost:3000/api/torrents
Unauthorized
```

**Comment by jesec** [comment]
See https://github.com/jesec/flood/blob/master/shared/schema/Config.ts. 

An authentication token is still required when auth is disabled. This is a standard security practice to protect users from session hijacking attacks. For instance, Transmission also requires similar procedures.

**Comment by ThinkChaos** [comment]
I see, I was looking at [config.cli.js](https://github.com/jesec/flood/blob/master/config.cli.js) so missed the comments.
I created a Wiki page with the link to the reference to help people find it in the future: [wiki/Configuration](https://github.com/jesec/flood/wiki/Configuration).

Thanks for the quick answer, and for investing time in maintaining this project!
