### ISSUE TITLE
Torrent added by file is disappearing from the list couple minutes after downloaded

### ISSUE THREAD

**Issue by r0bj** [jesec/flood#107]
Type: Bug Report

- [x] Try to follow the update procedure described in the README and try again before opening this issue.
- [x] Please check the [F.A.Q.](https://github.com/Flood-UI/flood/wiki/F.A.Q.).
- [x] Please check the [Troubleshooting](https://github.com/Flood-UI/flood/wiki/Troubleshooting) wiki section.

## Your Environment

- Version used:
  - Version from docker (stable release) `v4.1.2`
- Environment name and version:
  - Web browser `chrome 87.0.4280.67 `

## Summary

Torrent added by file is disappearing from the list couple minutes after downloaded. The same torrent downloaded by URL (magnet link) works fine, stays on the list.

## Expected Behavior

Torrent added by file is present on the list until manually deleted.

## Steps to Reproduce

1. Add torrent by file
2. Wait for torrent downloaded
3. After couple of minutes torrent disappears from the list

I'm not sure how to debug it better so I could provide better information. In flood logs there is nothing except:
```
GET /api/activity-stream?historySnapshot=FIVE_MINUTE 200 2.760 ms - -
```

**Comment by bbashy** [comment]
This is for rTorrent?  Using the latest version and I'm not getting this problem.

**Comment by r0bj** [comment]
Yes, it's for rtorrent.

**Comment by jesec** [comment]
This is 100% related to your rTorrent configuration (`.rtorrent.rc`). I am fairly certain that Flood has nothing to do with this. Many rTorrent configuration templates contain rules that delete or move torrent after completion.

**Comment by r0bj** [comment]
That may be the case, I'm going to test it a little deeper.
Does flood delete torrent file from `/home/download/.local/share/flood/temp` after torrent is downloaded?

**Comment by jesec** [comment]
It does. However, by the time, the torrent was already added to rTorrent.

**Comment by r0bj** [comment]
So my understanding of this issue:
1. rtorrent configuration was direct cause of this issue, particular lines:
```
schedule = untied_directory,5,5,stop_untied=
schedule = untied_directory,5,5,close_untied=
schedule = untied_directory,5,5,remove_untied=
```
2. previous version of flood I was using (https://github.com/Flood-UI/flood/releases/tag/v1.0.0) used different method of adding torrents to rtorrent, directly via SCGI rather than creating torrent file in temporary directory on filesystem and passing path to rtorrent. After torrent was downloaded, flood removed torrent file from temp directory which caused rtorrent to delete torrent from torrents list.
This is why my rtorrent configuration caused issue with current flood version.

Thanks for help @jesec
