### ISSUE TITLE
Error in events.js?

### ISSUE THREAD

**Issue by bbashy** [jesec/flood#108]
Type: Bug Report

- [x] Try to follow the update procedure described in the README and try again before opening this issue.
- [x] Please check the [F.A.Q.](https://github.com/Flood-UI/flood/wiki/F.A.Q.).
- [x] Please check the [Troubleshooting](https://github.com/Flood-UI/flood/wiki/Troubleshooting) wiki section.

## Your Environment

- Version used:
  - Version (stable release) `v4.1.2`
  - Commit ID (development release) `9cb821bb3072f7cda48f8d3910c4344b1aee8469`
- Environment name and version:
  - Node.js version `v12.19.1`
  - npm version `6.14.8`
  - Web browser `Firefox 83.0` (not related as it happened in the background)
- Operating System and version: macOS Big Sur (not related as it happened in the background)

## Summary

Over night it crashed (second time).

```
Nov 23 21:10:58 Host npm[27783]: POST /api/torrents/delete 200 79.444 ms - -
Nov 23 21:10:59 Host npm[27783]: PATCH /api/settings 200 1.700 ms - 26
Nov 23 21:12:45 Host npm[27783]: GET /api/activity-stream?historySnapshot=FIVE_MINUTE 200 1.024 ms - -
Nov 24 02:47:58 Host npm[27783]: events.js:291
Nov 24 02:47:58 Host npm[27783]:       throw er; // Unhandled 'error' event
Nov 24 02:47:58 Host npm[27783]:       ^
Nov 24 02:47:58 Host npm[27783]: Error: unexpected end of file
Nov 24 02:47:58 Host npm[27783]:     at Zlib.zlibOnError [as onerror] (zlib.js:180:17)
Nov 24 02:47:58 Host npm[27783]: Emitted 'error' event on Gunzip instance at:
Nov 24 02:47:58 Host npm[27783]:     at errorOrDestroy (internal/streams/destroy.js:108:12)
Nov 24 02:47:58 Host npm[27783]:     at Gunzip.onerror (_stream_readable.js:755:7)
Nov 24 02:47:58 Host npm[27783]:     at Gunzip.emit (events.js:314:20)
Nov 24 02:47:58 Host npm[27783]:     at Zlib.zlibOnError [as onerror] (zlib.js:183:8) {
Nov 24 02:47:58 Host npm[27783]:   errno: -5,
Nov 24 02:47:58 Host npm[27783]:   code: 'Z_BUF_ERROR'
Nov 24 02:47:58 Host npm[27783]: }
Nov 24 02:47:58 Host npm[27783]: npm ERR! code ELIFECYCLE
Nov 24 02:47:58 Host npm[27783]: npm ERR! errno 1
Nov 24 02:47:58 Host npm[27783]: npm ERR! flood@4.1.2 start: `node --use_strict dist/index.js "--port" "3005"`
Nov 24 02:47:58 Host npm[27783]: npm ERR! Exit status 1
Nov 24 02:47:58 Host npm[27783]: npm ERR!
Nov 24 02:47:58 Host npm[27783]: npm ERR! Failed at the flood@4.1.2 start script.
Nov 24 02:47:58 Host npm[27783]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Nov 24 02:47:58 Host npm[27783]: npm ERR! A complete log of this run can be found in:
Nov 24 02:47:58 Host npm[27783]: npm ERR!     /home/user/.npm/_logs/2020-11-24T02_47_58_770Z-debug.log
```

## Steps to Reproduce

Not sure how to reproduce, looks just like a code bug instead of something that can happen by doing something.

**Comment by jesec** [comment]
Flood doesn’t use Gzip as far as I know. I think there might be some bugs in Flood’s dependencies. I will take a look.

**Comment by bbashy** [comment]
Hasn't happened since 30th Nov running `v4.2.0`.

**Comment by jesec** [comment]
Good to know!

It is probably related to https://github.com/fent/node-feedsub/issues/57. 

07e428d1baa1fca5f31580f52ef1d1ac772e828b upgraded `feedsub` to a newer version. That fixed the problem I believe.

**Comment by bbashy** [comment]
Yeah I did see you dump the deps so hoped that would be your solution.

I'll say this is fixed now. Thanks.
