### ISSUE TITLE
Peers list columns display issue with IPv6 and excessively precise progress %

### ISSUE THREAD

**Issue by angristan** [jesec/flood#109]
Type: Bug Report

- [x] Try to follow the update procedure described in the README and try again before opening this issue.
- [x] Please check the [F.A.Q.](https://github.com/Flood-UI/flood/wiki/F.A.Q.).
- [x]  Please check the [Troubleshooting](https://github.com/Flood-UI/flood/wiki/Troubleshooting) wiki section.

## Your Environment

- Version used: 4.2.0
- Environment name and version:
  - Node.js version: `14.15.1`
  - npm version `6.14.8`
  - Web browser `Chrome  87.0.4280.67  on macOS`
- Operating System and version: Debian 10 (server)

## Issue

The peers list look great when there are only IPv4:

![screenshot_2020-11-28_01-15-56@2x](https://user-images.githubusercontent.com/11699655/100489924-baa02b80-3117-11eb-987c-8a4acaa9ca9e.png)

But not with IPv6 and a progress percentage that is a bit too precise I think 🙂

![screenshot_2020-11-28_01-14-31@2x](https://user-images.githubusercontent.com/11699655/100489929-c4299380-3117-11eb-974f-faa4b78f2594.png)

**Comment by jesec** [comment]
Hi @angristan ,

Can you try the latest release?

**Comment by angristan** [comment]
Sorry, I don't have any flood server running currently :( Thanks for the fix though 👍

**Comment by angristan** [comment]
![screenshot_2021-01-22_02-12-37](https://user-images.githubusercontent.com/11699655/105562976-c3c70680-5d1c-11eb-9285-72eb6ee319ca.png)

LGTM for the percentage 🙂 

IPv6 kind of mess up all the layout, not much can be done about that, except maybe making the whole popup larger so that lines aren't wrapped? 😕

**Comment by jesec** [comment]
That would not work well for mobile devices.

**Comment by angristan** [comment]
Indeed :( What about limiting the cell width and wrapping the address with an ellipsis?

**Comment by jesec** [comment]
It would be a good idea.

BTW: What's your torrent client in https://github.com/jesec/flood/issues/109#issuecomment-765803002? I think Flood has to tweak the API response to remove [].

**Comment by angristan** [comment]
It was rTorrent. I moved to qBT since and indeed I don't have the []

**Comment by jesec** [comment]
Checkout 4d51ce42f20c53222bb145145e160fda06d63f07 and c37b6ea86aca8002ef764a3ecdd727d5001eee51.

**Comment by angristan** [comment]
Perfect! That's what I had in mind but couldn't find the correct CSS rules. Thanks!

![screenshot_2021-02-03_13-55-09](https://user-images.githubusercontent.com/11699655/106750042-98e78700-6627-11eb-993a-a9eff6661909.png)
