### ISSUE TITLE
The added date is mm/dd/yyyy, should be localised and/or configurable

### ISSUE THREAD

**Issue by PaulBags** [jesec/flood#123]
---
name: '🐛 Bug Report'
about: 'Report a general bug'
---

Type: Bug Report

- [ ✅ ] Try to follow the update procedure described in the README and try again before opening this issue.
- Also checked Config.ts in case there was some hidden setting I was missing (though localisation should be per user).

## Your Environment

- Version used:
  - Version (stable release)
    4.3.1
  - ~~Commit ID (development release) `git --no-pager log -1`~~
- Environment name and version:
  - Node.js version `node --version`
    v12.19.0
  - npm version `npm --version`
    7.1.0
  - Web browser `name and version`
    Firefox version 83.0
- Operating system and version:
    Windows 10 v20H2
- Torrent client and version:
    

## Summary: dates are wrong
For me mm/dd/yyyy is specifically wrong, confusing, & neigh unreadable. yyyy-mm-dd would be my preference (and an international standard, readable by everyone 😊) but even dd/mm/yyyy would be better.

Edit: I'm updating this to a bug report, because frankly the date format is completely incorrect if being tied to the language English. The date format used is *American*.

## Possible Solution
My solution would be a place for a setting in `settings > user interface`, directly under the language setting.
Could be a drop down menu with predetermined formats, a field for entering a custom format - or both, with custom being an option in the drop down menu.

**Comment by jesec** [comment]
It depends on your language. 

I tried different languages, and it seems that the date is properly formatted.

English:
![image](https://user-images.githubusercontent.com/11585141/102015272-83777e80-3d95-11eb-9c69-fb7f7661a2cd.png)

日本語：
![image](https://user-images.githubusercontent.com/11585141/102015296-a73ac480-3d95-11eb-9d9e-836346ffbde3.png)

**Comment by PaulBags** [comment]
That's not how this works, date formats are tied to countries - not languages.

There are english speaking countries that officially use dd/mm/yyyy and only dd/mm/yyyy. Language selection is not an answer.

And besides, people may have preferences that differ from their localisation.

**Comment by PaulBags** [comment]
Hmm. I've been poking around crowdin, but I can't figure out how to touch english or add any of the localised englishes as a target language so that I can fix the date.

I assume crowdin is the correct tool, unless I have to go off and fix the date formatter in react...

**Comment by PaulBags** [comment]
I'm updating this to a bug. English language uses dmy, a similar language called American uses mdy. The localisation for English is incorrect and since it's the projects root language it's uneditable.

**Comment by PaulBags** [comment]
Oh and well I'm here: language won't say on specifically English. Reverts to Automatic.

**Comment by PaulBags** [comment]
Ah, I see that client/src/javascript/util/detectLocale.ts is specifically ignoring localisations. That won't help.

**Comment by PaulBags** [comment]
Console output showing overriding to be the source of the problem:
```
(new Date()).toLocaleDateString();
"14/12/2020"
Intl.DateTimeFormat().format(new Date())
"14/12/2020"
Intl.DateTimeFormat('en').format(new Date())
"12/14/2020"
```

**Comment by jesec** [comment]
Currently Flood uses [FormattedDate](https://formatjs.io/docs/react-intl/components/#formatteddate) of `react-intl`. It uses the current language settings, and I don't think it has the capability to specify different date format.

**Comment by PaulBags** [comment]
"It uses the current language settings"

It's not, check your own code: flood is truncating locales.

**Comment by jesec** [comment]
detectLocale now respects the locale of user and passes it to the IntlProvider. Though, Flood still uses the old behavior if you specify language manually. I think it would be too much maintenance burden for the project if a separate manual selection menu needs to be added for locale.

**Comment by PaulBags** [comment]
Or a single very long list of "languages"/locales.

This is an elegant solution which is working well, thank you. I'm impressed.


P.S. if anyone *does* want to take this further I boiled the English locales down to four "types": en, en-CA, en-001, and en-150.

en uses `mdy` date formats and the decimal seperator `.`.
- locales: en, en-AS, en_BI, en_GU, en_MH, en_MP, en_PR, en_UM, en-US, en-US-POSIX, en_VI
en-CA uses `ymd` date formats and the decimal seperator `.`.
- locales: en-CA, en_SE, en-ZA
en-150 uses `dmy` date formats and the decimal seperator `,`.
- locales: en-<any in Europe>
en-001 uses `dmy` date formats and the decimal seperator `.`.
- locales: en-<rest of world>

But, frankly, that way lays madness.

**Comment by GitHubGeek** [comment]
Thanks guys, the dates look much better now in Flood. en-GB locale now shows dd/mm/yyyy

**Comment by lwbt** [comment]
Using a format that users of a certain locale typically expect is probably fine. But at least an option to switch to  [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) `YYYY-MM-DD` should be provided. I'm German, I often use English and whenever I have to use a date format it is ISO 8601 (`date -I` in bash scripts). Then I have one thing less to worry about.
