### ISSUE TITLE
Wrong mediainfo properties for a brand-new, stopped torrent

### ISSUE THREAD

**Issue by a-roussos** [jesec/flood#127]
Type: Bug Report

- [✅] Try to follow the update procedure described in the README and try again before opening this issue.

## Your Environment

- Version used:
  - Version (stable release) **4.3.1** (running in a docker container, image was pulled with `docker pull jesec/flood`)
  - Commit ID (development release) **not applicable**
- Environment name and version:
  - Node.js version **15.3.0**
  - npm version **7.0.14**
  - Web browser **Firefox 84.0**
- Operating system and version: **Windows 10 2004**
- Torrent client and version: **rTorrent 0.9.6**

- Docker `run` command: `docker run -d --name flood -p 127.0.0.1:31000:3000 -v /home/download/rtorrent:/home/download/rtorrent -v /home/download/.local/share/flood:/home/download/.local/share/flood jesec/flood --allowedpath /home/download/rtorrent`

## Summary

Accessing the "Mediainfo" tab on the "Torrent Details" page/modal for a brand-new, stopped torrent with a destination path equal to the default download directory results in an unexpected listing of `mediainfo`-gathered properties for _**all**_ completed files in the default destination directory and below. To be honest, I reckon this is probably not that big of a deal as people are not really expected to access the "Mediainfo" tab for a stopped torrent they've just added. Nevertheless, I'm raising this issue because I like Flood and wish to make it just a little bit better 🙏 

## Expected Behavior

The "Mediainfo Output" should be empty for a torrent that has just been added and is in the stopped state.

## Current Behavior

You get a listing of properties for all completed files residing in the default download directory and below, as per this screenshot:
![flood-mediainfo](https://user-images.githubusercontent.com/25583206/102709404-06776800-42b3-11eb-9cd8-98957973c166.png)
_NOTE: I used Firefox's Web Developer tools to resize the modal so that you can see all the information._

## Possible Solution

I think it has to do with how the following gets evaluated:
https://github.com/jesec/flood/blob/1b375ebfc5c610b3889800571ff90df388545e7c/server/routes/api/torrents.ts#L691
If I'm reading this right, a new torrent that has not yet started will result in `contentPath` being equal to the base directory of the torrent. Which, for torrents saved in the default download directory, will result in the unexpected behaviour outlined above. AFAICT this happens because the `mediainfo` command will recursively try to gather info for all files under the directory passed as an argument.

## Steps to Reproduce

0. (pre-requisite) Ensure that you have at least one completed torrent in the default download directory
1. Add a new torrent: "Destination" must be equal to Flood's Default Download Directory and "Start Torrent" must be unchecked
2. Double-click on the torrent to bring up the torrent details modal (or right-click ➡️ "Torrent Details")
3. Click on the Mediainfo tab on the left hand side
4. Observe that the "Mediainfo Output" section on the right displays information for all completed files residing in the default download directory and below

## Context

I was viewing the "Torrent Details" page for a torrent I've just added (and had not yet started), and was curious to see what would get reported under the "Mediainfo" tab.

**Comment by jesec** [comment]
If the file/directory doesn’t exist, per the existing logics, Flood will execute mediainfo on the whole directory. It is implemented this way because there is no reliable way to handle single/multi-file and base directory/sub directory cases. 

If possible, can you share some ideas about potential solutions?

**Comment by vain4us** [comment]
Not sure about how the actual code would look like, but you could implement a pre-check that checks if the torrent has actually downloaded anything. If so, do mediainfo, if not, return error in mediainfo field ("torrent must be started first"). 

Not sure how hard this would be tbf.

**Comment by jesec** [comment]
> Not sure about how the actual code would look like, but you could implement a pre-check that checks if the torrent has actually downloaded anything. If so, do mediainfo, if not, return error in mediainfo field ("torrent must be started first").
> 
> Not sure how hard this would be tbf.

That would introduce a dependency on torrent properties. It could be a bit resource consuming to fetch torrent list unnecessarily.

**Comment by Arno500** [comment]
> > Not sure about how the actual code would look like, but you could implement a pre-check that checks if the torrent has actually downloaded anything. If so, do mediainfo, if not, return error in mediainfo field ("torrent must be started first").
> > Not sure how hard this would be tbf.
> 
> That would introduce a dependency on torrent properties. It could be a bit resource consuming to fetch torrent list unnecessarily.

But on the other side this is probably lighter than running MediaInfo for EVERY file in the folder, especially if there is a lot.

**Comment by jesec** [comment]
> > > Not sure about how the actual code would look like, but you could implement a pre-check that checks if the torrent has actually downloaded anything. If so, do mediainfo, if not, return error in mediainfo field ("torrent must be started first").
> > > Not sure how hard this would be tbf.
> > 
> > 
> > That would introduce a dependency on torrent properties. It could be a bit resource consuming to fetch torrent list unnecessarily.
> 
> But on the other side this is probably lighter than running MediaInfo for EVERY file in the folder, especially if there is a lot.

That makes sense.

**Comment by jesec** [comment]
@a-roussos I believe that the issue has been resolved by 4ac31e9. Can you test the latest build?

**Comment by a-roussos** [comment]
Thank you, @jesec! I just pulled the latest docker image (`jesec/flood:master`), and now I get this error message:

![flood-mediainfo-2](https://user-images.githubusercontent.com/25583206/104085774-ae50d780-525a-11eb-8057-562e379a6580.png)

If I run `docker exec -it flood sh` to launch a shell inside the Flood container I can find Mediainfo in `/usr/bin/mediainfo`, and the `$PATH` variable (for the `download` user) includes `/usr/bin`. So, I'm not sure what's causing the error message.

**Comment by jesec** [comment]
> Thank you, @jesec! I just pulled the latest docker image (`jesec/flood:master`), and now I get this error message:
> 
> ![flood-mediainfo-2](https://user-images.githubusercontent.com/25583206/104085774-ae50d780-525a-11eb-8057-562e379a6580.png)
> 
> If I run `docker exec -it flood sh` to launch a shell inside the Flood container I can find Mediainfo in `/usr/bin/mediainfo`, and the `$PATH` variable (for the `download` user) includes `/usr/bin`. So, I'm not sure what's causing the error message.

`An error occurred` message and the suggestion is hardcoded. `No such file or directory` is the real error message. It is the expected message when the file does not exist (yet).

**Comment by a-roussos** [comment]
That's great, thanks for clarifying! I consider this issue closed. Thanks again for your efforts in resolving this. 👍
