### ISSUE TITLE
Internal server error when adding torrents

### ISSUE THREAD

**Issue by brezinajn** [jesec/flood#152]
Type: Bug Report

- [x] Try to follow the update procedure described in the README and try again before opening this issue.

## Your Environment

- Version used: 4.3.1
- Environment name and version: `flood-linux` pre packaged executable
- Operating system and version: Ubuntu 20.04.1
- Torrent client and version: qbittorrent-nox 4.3.1

## Summary

When adding torrent (via magnet link) call to `api/torrents/add-urls` ends up with status code 500 and empty object body. Works fine in 4.3.0

## Steps to Reproduce

See `Summary`

**Comment by jesec** [comment]
I am not able to reproduce the issue. It is unlikely that such basic case would fail given that Flood has been [tested](https://github.com/jesec/flood/blob/master/server/.jest/qbittorrent.setup.js) against a fresh and real qBittorrent instance. Test results of 4.3.1 is [ALL PASSED](https://github.com/jesec/flood/runs/1530114945):

```
PASS qbittorrent server/routes/api/torrents.test.ts (14.788 s)
  POST /api/torrents/add-urls
    ✓ Adds torrents via URLs with incorrect options (19 ms)
    ✓ Adds torrents to disallowed path via URLs (5 ms)
    ✓ Adds torrents via URLs (5135 ms)
    ✓ GET /api/torrents to verify torrents are added via URLs (10 ms)
```

Unlike rTorrent implementation (which downloads torrent in Flood before the path is passed), Flood passes URLs directly to qBittorrent:

https://github.com/jesec/flood/blob/055673738a35c47ddcbb26132288bdae7cd21bbc/server/services/qBittorrent/clientGatewayService.ts#L60-L77

Try the latest rolling build first. There are some unreleased changes that may solve the problem or make it easier to debug. Rolling builds (standalone executables) are available as artifacts of [Github Actions workflows](https://github.com/jesec/flood/actions?query=workflow%3A%22Publish+rolling+build%22). 

Additionally, try to use "Network" of F12 (DevTools) of the browser to intercept the request.

**Comment by brezinajn** [comment]
Works fine with latest rolling build. Still fails with 4.3.1, so it seems there is something going on. Anyway closing this issue. Thanks
