### ISSUE TITLE
no db  Folder

### ISSUE THREAD

**Issue by korncola** [jesec/flood#153]
Type: Bug Report

- [ ] Try to follow the update procedure described in the README and try again before opening this issue.

## Your Environment

- Version used:
  - Commit ID c37c32b058de1bf8eb5d2c8fc883fc18cadcd717
- Environment name and version:
  - Node.js version 15.5.1
  - npm version 7.3.0
- Operating system and version: Arch Linux

## Summary
Cant reset password as states in FAQ cause i dont have db folder under server.
Also deleting whole flood folder and do new git clone does not revert it. still asking for password.
## Expected Behavior
1) option to disable auth
2) PAM logins
3) user mangement in webinterface
4) up to date faq

## Current Behavior
outdated faq
no sign of my user entry (grep -r username returns nothing)
and yeah shit
## Possible Solution
one of (better all)
1) option to disable auth
2) PAM logins
3) user mangement in webinterface
4) up to date faq

## Steps to Reproduce
use chrome password suggestion on http :-) (it does not save its suggestion)

**Comment by korncola** [comment]
grepped whole hard drive - found the file:
`~/.local/share/flood/db/users.db`

Peronsal rant: This is one example for linux sometime being as annoying as windows when using this damn "%AppData%' Unix variant...
But at least document it :-)

**Comment by jesec** [comment]
FAQ of this project very clearly documented that db is in rundir. 

https://github.com/jesec/flood/wiki/F.A.Q.

Meanwhile, `flood —help` and [shared/schema/Config.ts](https://github.com/jesec/flood/blob/master/shared/schema/Config.ts) tells you where rundir is, documented in [configuration section of README](https://github.com/jesec/flood#configuration). 

I believe either you are not reading the documentations careful enough or you read a legacy version of the documentations.

**Comment by korncola** [comment]
rundir should be the folder where i issued npm start.
At least document it clearly in the same FAQ that rundir by default is ~/.local/share/flood to make it easier to find. What you said is technically correct but not very user friendly.

**Comment by jesec** [comment]
> rundir should be the folder where i issued npm start and not a folder which is used for sharing assets between multiple packages:
> https://www.freedesktop.org/software/systemd/man/file-hierarchy.html
> At least document it clearly in the same FAQ that rundir by default is ~/.local/share/flood to make it easier to find. What you said is technically correct but not very user friendly.

It should never be the current directory. Flood is intended to be installed globally (to `/usr(/local)/bin`) for most users. In most cases, a user simply runs `flood` (instead of `npm start`).

Extra security caution is advised when you compile and run Flood with the same user given that typically a user who can compile sources has write access to Flood's programs, which may allow an attacker to overwrite Flood's control flows by downloading to Flood's programs, should there be a security breach. 

The documentation is already quite clear IMO. Wiki is open for anyone to contribute. You may do so if you wish.

**Comment by korncola** [comment]
Thank you very much for your reply (and your continous work on this project)
The misunderstanding i think come from i am long time user of flood and your fork, before it was available via npm/npx. Ran into my "problem" as i just recently reinstalled cause i changed the instance it is running on.

Thank you also for your security hint. I don't run flood with same user it is compiled with, i have a systemd unit and use a system user (the nobody :) )

I think the iussue can be closed, i am happy to contribute to the wiki and make it bit clearer what rundir is.
