### ISSUE TITLE
Flood inaccessible on kiwi browser with Uncaught SyntaxError: Unexpected token ?

### ISSUE THREAD

**Issue by euri10** [jesec/flood#156]
Type: Bug Report

- [x] Try to follow the update procedure described in the README and try again before opening this issue.

## Your Environment

- Version used:
  - Version (stable release) : 4.3.1
- Environment name and version:
  - Node.js version `node --version` 15.3.0
  - npm version `npm --version` 7.0.14
  - Web browser `name and version` Kiwi Browser
- Operating system and version: this runs in docker jesec/rtorrernt so I guess it's alpine
- Torrent client and version: rtorrent 0.9.8

## Summary

I was testing several browsers I use on android after I migrated my old flood install and found this fork (awesome one by the way, migration was flawless !) and found one instance where the UI cant be access because of this js error: `Uncaught SyntaxError: Unexpected token ?`

it dosent happen on other browsers like Brave, Chrome but Kiwi being a fork of chromium as well I figured I'd report it.

The console dev tools shows where  the js error is, see screen below

## Current Behavior

this error:

![20210110_0835_1920x1080_1610264112](https://user-images.githubusercontent.com/1104190/104117362-0b16c580-5321-11eb-8660-860ae2b23739.png)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by jesec** [comment]
I am aware of the issue. Unfortunately, Kiwi’s version of Chromium is too old to properly support some modern web standards. There is nothing I can do here.

**Comment by euri10** [comment]
thanks for the answer @jesec , hopefully they update their chromium version !
