### ISSUE TITLE
Invalid peer client name and/or version

### ISSUE THREAD

**Issue by angristan** [jesec/flood#167]
Type: Bug Report

- [x] Try to follow the update procedure described in the README and try again before opening this issue.

## Your Environment

- Version used: https://github.com/jesec/flood/commit/23b689b7f7d86c3985952b80428d6ba204c2298f
- Environment name and version:
  - Node.js version `v14.15.4`
  - npm version `6.14.10`
  - Web browser `Chrome 87`
- Operating system and version: macOS 11.1
- Torrent client and version: rtorrent 0.9.8

## Summary

Some peers' torrent clients are marked as unknown

## Expected Behavior

- Should show the client name, like rutorrent (here, `Flud`)
- Show valid version (here, `2.94`)
 
<img width="131" alt="screenshot_2021-01-23_11-13-31" src="https://user-images.githubusercontent.com/11699655/105575527-96a24480-5d6c-11eb-874c-37cd3f6deaf8.png">

## Current Behavior

<img width="149" alt="screenshot_2021-01-23_11-13-40" src="https://user-images.githubusercontent.com/11699655/105575534-9ace6200-5d6c-11eb-9820-cf0396c1c409.png">

**Comment by jesec** [comment]
Flood uses response from the torrent client. 

https://github.com/jesec/flood/blob/23b689b7f7d86c3985952b80428d6ba204c2298f/server/services/rTorrent/constants/methodCallConfigs/torrentPeer.ts#L9

I believe ruTorrent uses its own torrent client mapping: 

https://github.com/Novik/ruTorrent/blob/304996ddf9bc250bc6704b5365334e75975a3f10/js/common.js#L1105

**Comment by angristan** [comment]
I see! Thanks.

**Comment by jesec** [comment]
Resolved by https://github.com/jesec/libtorrent/commit/8529972281ce77ec0c77710204268d776de7dd9e.

**Comment by angristan** [comment]
Thanks a lot!

(wow, you even maintain a fork of libtorrent)
