### ISSUE TITLE
flood on qbittorrent can't change location when adding new torrent

### ISSUE THREAD

**Issue by lilws** [jesec/flood#189]
- Version used:
  - Version (stable release): v4.4.0
- Environment name and version:
  - Node.js version `node --version`: 15.7.0
  - npm version `npm --version`: 7.4.3
  - Web browser `name and version`: Chrome stable
- Operating system and version: Synology DSM 6.2.3 - run flood in docker
- Torrent client and version: qbittorrent 4.3.3

## Summary

I read in the change log of flood 4.4.0 is that it support isCompleted (skip_checking) so I tried to add a torrent that is already has its data downloaded. But when I change the location to something else, it would fall back to the default locattion.

Actually, I've never used add new torrent from flood, because I have qbittorrent watch a folder to download to correct location already. But since I love to use flood so I check this features cause of skip_checking. And this bug happen even adding new torrent, it all falls back to default location.

## Expected Behavior

I download a torrent and want to save to /downloads/software rather then its default location.

## Current Behavior

It downloads that torrent and save to /download/movies which is the default location.

## Steps to Reproduce

1. Add new torrent by file
2. Change default save location
3. Add Torrent

**Comment by jesec** [comment]
I failed to understand the issue. Flood does not have `default location`. It does save last used destination for later uses, but the only way to change that is to successfully add with different destination (or via a manual API call). It can not be "changed".

**Comment by jesec** [comment]
Are you actually adding the torrent with Flood frontend ? Doesn't Flood use destination specified via Textbox?

**Comment by lilws** [comment]
That is strange, I just tried again and it can't change the location when adding. I have recorded a video but it 15MB so can't upload here.

I use jesec/flood with linuxserver/qbittorrent.

**Comment by lilws** [comment]
If I change the location in resource settings before adding a new torrent, it will go to that default location

**Comment by jesec** [comment]
You can upload the video to YouTube.

**Comment by lilws** [comment]
I uploaded it to youtube, it will need sometimes to render to HD

[https://youtu.be/DpWusHWcbX8](url)

**Comment by jesec** [comment]
Interesting. Can you open DevTools, go to Network tab and see if the request contains proper destination?

**Comment by lilws** [comment]
I've just check it, the add-files header contains proper destination I want to.

**Comment by lilws** [comment]
Ok, I'm so sorry here. This is my fault in qbittorrent config. I just create another qbittorrent content and testing with the same flood container. This is just because of Torrent Management Mode turn ON, it override any input of user to the default one.
