### ISSUE TITLE
Add "Seeding" in Status Filter

### ISSUE THREAD

**Issue by vongola12324** [jesec/flood#19]
Type: Feature Request

- [ ] If you want to contribute to the project please review the [contributing guidelines](https://github.com/Flood-UI/flood/blob/master/.github/CONTRIBUTING.md).

## Summary
Flood can now filter the torrent which is still downloading, active, or inactive. 
Can we add a "Seeding" status in the status filter?
This might be helpful for those people who want to know the torrent has been downloaded but is still seeding (or uploading).

## Idea of implementation
It seems we have "seeding" class in `client/src/javascript/util/torrentStatusClasses.js`. 
Does that mean we can know the torrent has downloaded but still seeding?
If that is the case, maybe we can add "Seeding" into the status filter in the sidebar.

**Comment by jesec** [comment]
I think inactive filter is designed for that. An additional seeding filter may be duplicative. We would have to redesign/rearrange filters to accommodate that. A potential option is to replace inactive/active filters. What do you think?

**Comment by vongola12324** [comment]
It seems that "active" is including all status which the torrent has network traffic, like "downloading" and "seeding", and "inactive" is including all status which the torrent do not have network traffic, like "stopped", "completed", and "no peer connected". We already have a downloading filter, so I think an additional seeding filter might not be duplicative.
Also, we should not replace inactive/active filters, because those filter can let us know that the torrents are still working or not.

**Comment by jesec** [comment]
That makes sense. Certainly I will take a look at it.

**Comment by vongola12324** [comment]
Thank you!! 👍 
I can find out which torrent is still seeding now. 🎉
