### ISSUE TITLE
Flood adds / at the beginning of the destination path without showing it in the destination path

### ISSUE THREAD

**Issue by ramiran2** [jesec/flood#194]
Type: Bug Report

## Your Environment

- Version used:
  - Version (stable release) : 4.4.1 (with NPM)
  - Commit ID (development release) `git --no-pager log -1` : 
- Environment name and version:
  - Node.js version `node --version : v15.8.0
  - npm version `npm --version : v7.5.3
  - Operating system and version: Fedora 33 (Server Edition) Kernel 5.10.13-200.fc33.x86_64
- Torrent client and version: qBittorrent v4.3.3
  - Operating system and version: Windows 10 Version 20H2 Build 19042.804
- Web browser `name and version : Microsoft Edge Version 88.0.705.63

## Possible Solution

Remove the path correction code, Improve the path correction to recognize a windows path "A:/", Make path correction code Toggleable by the user.

## Steps to Reproduce

1. Install flood on Linux
2. Install Torrent Client on Windows
3.  qBittorrent Errors out due to the path looking like /A:/Torrent/Downloads/ when it expects A:/Torrent/Downloads/

**Comment by jesec** [comment]
This is not a supported case. README very clearly notes that you have to run Flood and torrent client on the same machine.

**Comment by ramiran2** [comment]
ok but everything works this is the only issue,

**Comment by jesec** [comment]
Flood needs the same filesystem context, which is not achievable when Flood is not on the same platform as torrent client. You may get a minimally working web UI but many features DO break.

**Comment by ramiran2** [comment]
i understand that but none the less why do even need to add / in the path if it does not have one? why not add it before the user adds the torrent

**Comment by jesec** [comment]
Because that’s how Unix path works. This is the expected behavior of path expansion function when executed on a Linux machine. It simply can’t go other way. Otherwise, things can break for people who do have a **correct** setup.
