### ISSUE TITLE
No units displayed when the interface is in French

### ISSUE THREAD

**Issue by MrBerthier** [jesec/flood#198]
## Your Environment
- [X]  Ubuntu 20.10
- [X] rTorrent 0.9.8
- [X]  Flood 4.4.1

## Summary
Flood's interface doesn't show any units for upload and download speeds when I switch the interface to French. For example, it displays "55,5/s", the "kB" is missing. It seems to affect only upload and download speeds. I don't have the issue when I change the language to English or German.

## Expected Behavior
Upload and download speeds unit are diplayed : 55,5 kB/s

## Current Behavior
Upload and download speeds unit are not diplayed : 55,5 /s

## Screenshots
![2021-02-13_18h01_45](https://user-images.githubusercontent.com/79017046/107856548-25185c00-6e29-11eb-9709-8984b3632c61.png)
![2021-02-13_18h02_06](https://user-images.githubusercontent.com/79017046/107856550-26498900-6e29-11eb-804b-3beda61442ed.png)

**Comment by jesec** [comment]
cc: @Carryozor 

Apparently there is a mistranslation of templates:
https://github.com/jesec/flood/commit/fd571787bd30ee87784f1570b4f045a1b2d90055

You may improve the translations via Crowdin.

**Comment by MrBerthier** [comment]
Thanks for the quick analysis!
By the way, the unit should be int this case "ko" not "kB" as I mentioned.

**Comment by Carryozor** [comment]
The issue is that i translated a variable he asked me (was too fast didn't saw it was one) it should be good now for the next version sorry. The value will be ko,mo,go and so on don't worry about this.

**Comment by MrBerthier** [comment]
Excellent! Thank you!

**Comment by Carryozor** [comment]
Tryed it, it work like a charm now :).

**Comment by MrBerthier** [comment]
Excellent news, I can wait to get my hands on the update! Any ideas on when it live be available?

**Comment by Carryozor** [comment]
you can simply clone the depot if you don't wanna wait. For the update i don't know @jesec is the only one who know (aside from god)

**Comment by tydoo** [comment]
Its done on new version.

You can close ;)

**Comment by MrBerthier** [comment]
Yes, it's perfect! Thanks!
