### ISSUE TITLE
Checkbox falls out of display zone

### ISSUE THREAD

**Issue by m3r3nix** [jesec/flood#216]
Type: Bug Report

- [x] Try to follow the update procedure described in the README and try again before opening this issue.

## Your Environment

- Version used:
  - Version (stable release) 4.4.1
  - Commit ID (development release) `git --no-pager log -1`
- Environment name and version:
  - Node.js version `node --version` flood-linux-x64 single binary
  - npm version `npm --version`
  - Web browser `name and version` Firefox 85.0.2
- Operating system and version: Win 10 20H2
- Torrent client and version: rTorrent 9.8 jesec r4

## Summary

In the modal of "Set Torrent Location":
Translated text in Hungarian language is longer than the English one therefore the "Move data" checkbox falls out of display zone. One can't see if it's checked or not.
See attached picture below.
![image](https://user-images.githubusercontent.com/12776959/109021011-c7063700-76ba-11eb-892a-3bf95aed6376.png)

I was thinking about to give it a shorter translation text, but the given one is the perfect one.

## Expected Behavior

Possible to see the current state of the checkbox.

## Current Behavior

I can't see it.

## Possible Solution

Either change modal width to auto or reorder checkboxes into vertical order.

## Steps to Reproduce

1. Change display language to "Magyar"
2. Select a torrent and go to the context menu
3. Select "Áthelyezés"
4. Now you will see it.

**Comment by jesec** [comment]
This is indeed annoying. I plan to move those toggles to their own rows.

**Comment by deejayexe** [comment]
Yes this problem still occurs in Spanish, I hope they can solve it soon

**Comment by couquino** [comment]
I have the same problem with the French translation. It's the .modal__content__wrapper class that fixes the width to 500px, disabing the width attribute on the Chrome dev console fixes it, but nothing permanent
