### ISSUE TITLE
Cannot build using docker

### ISSUE THREAD

**Issue by zewelor** [jesec/flood#22]
Type: Bug Report

- [ ] Try to follow the update procedure described in the README and try again before opening this issue.
- [ ] Please check the [F.A.Q.](https://github.com/Flood-UI/flood/wiki/F.A.Q.).
- [ ] Please check the [Troubleshooting](https://github.com/Flood-UI/flood/wiki/Troubleshooting) wiki section.

## Your Environment

* Version used:
  + Version (stable release) `git --no-pager tag`
  + Commit ID (development release) `git --no-pager log -1`
* Environment name and version:
  + Node.js version `node --version`
  + npm version `npm --version`
  + Web browser `name and version`
* Operating System and version:

## Summary

When doing docker build I get following error. Not sure how to proceed with it, doesn't seem to respect docker build args

```
Step 13/21 : RUN npm run build &&     npm prune --production
 ---> Running in 63b34291b8ef

> flood@3.0.0 build /usr/src/app
> node client/scripts/build.js

/usr/src/app/config.js:10
  secret: process.env.FLOOD_SECRET || CHANGE_ME,
                                      ^

ReferenceError: CHANGE_ME is not defined
    at Object.<anonymous> (/usr/src/app/config.js:10:39)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/usr/src/app/client/config/env.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
```

## Expected Behavior

Respect build-args or skip requirement to set flood_secret during docker build ( only need to set it when running built docker )

## Steps to Reproduce

1.
2.
3.
4.

**Comment by jesec** [comment]
See https://github.com/jesec/flood/security/advisories/GHSA-jx7m-jg3c-5p2f.

Default server secret is no longer provided. You would have to provide one.

Ideally this should not impair "build" as secret is only used for server. Still, it is probably better to exit early to be safe. 

Current Dockerfile is quite outdated. It can probably be updated to use the new cli interface. New cli interface can take environment variables as `FLOOD_OPTION_*=` and it automatically generates secret at start. See https://github.com/jesec/flood/projects/1#card-43716916. I plan to work on this when I have time but PRs are welcomed too.

**Comment by jesec** [comment]
Some additional details on the `secret` security hazard: 

Flood uses a `jwt` cookie to authenticate users and decide whether to allow calls to its sensitive APIs (eg. add-files). 

![image](https://user-images.githubusercontent.com/11585141/91423448-1fcf5100-e88b-11ea-826b-cdb4ea98bb49.png)

As you can see, if attacker has your `secret`, they can easily impersonate as any user on this Flood instance. Flood grants requests as long as this token is signed by server's `secret` so attacker don't even have to know an existing username. 

All they have to do is to add `jwt: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpYXQiOjE1MDAwMDAwMDAsImV4cCI6MTkwMDAwMDAwMH0.9q2bgDRefxYInARRRmb37brDQo6SMbCO_jcka9tBFcs` to their cookie and they would have full access to all Flood instances which use `flood` as server secret. 

For example, an authenticated user can, with file access privileges of Flood: 
- create a cronjob in /etc/cron.d that spawns a shell
- add any ssh key to /home/$USER/.ssh/authorized_keys and login over ssh
- overwrite /home/$USER/.bashrc to execute commands on the next login of the user
- overwrite code of flood itself which will execute the next time it is restarted

See: https://github.com/Flood-UI/flood/issues/588, https://github.com/Flood-UI/flood/issues/589 and https://github.com/jesec/flood/wiki/Security-precautions. 

That's why changes are made to get rid of this security hazard.

**Comment by zewelor** [comment]
Thanks for detailed reply. I think for easier workaround, would be to change Dockerfile, as you said, to maybe FLOOD_SECRET=changeme and validate it during server run ? Validate if its not empty or changeme ?

**Comment by jesec** [comment]
secret is not used during `build`. Build time secret won’t affect the secret of runtime.

**Comment by Sparticuz** [comment]
Just throwing this in there... looking at your docker task on the projects board, I'd love the ability to not include rtorrent in the container and to be able to run it separately.

**Comment by jesec** [comment]
In note:
> Flood’s relationship to rTorrent is not truly server-client as it performs file ops itself and needs local direct access to files. It makes more sense to bundle rTorrent. (**Users can still disable rTorrent via a variable** if they can make sure the actual path and the “in-container” path is the same)

Also see https://github.com/jesec/flood/issues/13#issuecomment-678326666: 
> Flood's relationship with rTorrent is NOT truly server-client. Flood server performs file operations itself. As I already said, you need to make sure the Flood server itself has permissions/access to the files. That's especially important if you are using containers. You need to make sure Flood can access the files directly and Flood only uses the path provided by rTorrent so it needs to have the same filesystem context as rTorrent. If a file is "/path/to/a/file" to rTorrent, it has to be "/path/to/a/file" to Flood in order to get file operations working. It can't be "/mnt/some/different/path/file".

Users will have the ability to disable bundled rTorrent.

Admittedly, some minimalists probably don't want rTorrent bundled at all to make Docker image smaller. However, rTorrent itself is quite small (only several MBs). I think it is well worth it to bundle rTorrent.

**Comment by Sparticuz** [comment]
I've got this docker image working using the following docker-compose
```yaml
version: "3.7"
services:
  rtorrent:
    image: looselyrigorous/rtorrent
    volumes:
      - ~/docker/rtorrent/config:/config
      - ~/docker/rtorrent/session:/session
      - ~/docker/rtorrent/socket:/socket
      - /downloads:/downloads
  flood:
    image: jesec/flood
    depends_on:
      - rtorrent
    entrypoint: [
      "flood",
      "--host=0.0.0.0",
      "--noauth",
      "--baseuri=/flood/",
      "--secret=**************",
      "--rtsocket=/rtorrent.sock",
      "--allowedpath=/downloads"
    ]
    volumes:
      - ~/docker/rtorrent/socket/rtorrent.sock:/rtorrent.sock
      - /downloads:/downloads
    ports:
      - 3000:3000
```
(I've removed some things like port, and have an nginx ssl terminator that also does the auth.)

**Comment by NoLooseEnds** [comment]
@Sparticuz  Where do you store the config.js? It does not seem like it get saved to `/data` – placing one there does nothing either. And `/data` does not contain the db either.

It looks like it saves the db to `/home/download/.local/share/flood`

**Comment by Sparticuz** [comment]
> @Sparticuz Where do you store the config.js? It does not seem like it get saved to `/data` – placing one there does nothing either. And `/data` does not contain the db either.
> 
> It looks like it saves the db to `/home/download/.local/share/flood`

All my config takes place in the entrypoint command. What are you using config.js for?

**Comment by NoLooseEnds** [comment]
It's mostly preference I guess, and I would also like to keep the db on a permanent volume.

**Comment by jesec** [comment]
> It's mostly preference I guess, and I would also like to keep the db on a permanent volume.

https://github.com/jesec/flood/issues/54#issuecomment-706672204

**Comment by NoLooseEnds** [comment]
@jesec Thanks. Worked. :) 

(Now my only issue is getting it to work behind Traefik, but that for be for another day)

**Comment by jesec** [comment]
Hi @zewelor ,

The Dockerfile and configuration interfaces has been revamped. Is this issue still relevant?

**Comment by zewelor** [comment]
Works now thanks!
