### ISSUE TITLE
df timeout crashes flood server

### ISSUE THREAD

**Issue by gboudreau** [jesec/flood#229]
Type: Bug Report

## Your Environment

- Version used:
  - `flood@0.0.0-master.f8c671f`
- Operating system and version: docker image, `master-dbg` tag

## Summary

Docker container stops when `df -T` takes more than 2 secondes to execute

## Expected Behavior

When a timeout occurs with `df` (or any non-essential command really), an error should be logged, but the flood server should not crash.

## Current Behavior

flood server crashes, which stops the docker container.

## Steps to Reproduce

Not sure how you could reproduce `df` taking longer than 2s... Maybe you can just change the command on https://github.com/jesec/flood/blob/master/server/util/diskUsageUtil.ts#L42 to `sleep 3` or something..? That should at least reproduce the crash.

## Context

```
$ sudo docker exec -it rtorrent-flood time df -T
.../
Command exited with non-zero status 1
real	0m 1.40s
user	0m 0.00s
sys	0m 0.00s
```

I guess it sometimes take longer than the 2000ms timeout defined in https://github.com/jesec/flood/blob/master/server/util/diskUsageUtil.ts#L39

**Comment by jesec** [comment]
Can you test the latest build?

**Comment by gboudreau** [comment]
I can't reproduce the initial problem it seems.
Your fix looks pretty straightforward, so I think this issue can be closed now. I'll continue to monitor my log for a "failed to update" message, and report back if I see it, or if it somehow crashes again.
Cheers.
