### ISSUE TITLE
Responsive Bug Add Torrent

### ISSUE THREAD

**Issue by Whisper40** [jesec/flood#232]
Type: Bug Report

Reponsive problem of 24" screen 
![image](https://user-images.githubusercontent.com/30440458/110352462-40484700-8036-11eb-9e79-a01198bd2165.png)

It occures with docker image (tested today 08/03/2021 with this image) : jesec/flood:latest

**Comment by jesec** [comment]
Duplicate.

See #216. 

Feel free to close this issue.
