### ISSUE TITLE
ERR_INVALID_ARG_TYPE starting server

### ISSUE THREAD

**Issue by fulder** [jesec/flood#239]
Type: Bug Report

- [x] Try to follow the update procedure described in the README and try again before opening this issue.

## Your Environment

- Version used:
  - Version (stable release):  Current `master` branch (4.4.1)
  - Commit ID (development release) `git --no-pager log -1`: `4a7e63890c43cd42166bb5c7a0b8a9ef59fa5f76`
- Environment name and version:
  - Node.js version `node --version`: v15.10.0
  - npm version `npm --version`: 6.14.8
  - Web browser `name and version`: Can't reach web UI
- Operating system and version: FreeBSD 12.2-RELEASE-p2
- Torrent client and version: No client tested

## Summary

I'm trying to install the flood server following the readme but it fails while trying to start it up using the `npm start` command.

## Expected Behavior

Server is started and I should be able to reach the UI

## Current Behavior
Server start is crashing with the following error:
```
> flood@4.4.1 start /usr/home/rtorrent/flood
> node --use_strict dist/index.js

node:internal/fs/utils:637
    throw new ERR_INVALID_ARG_TYPE(propName, ['string', 'Buffer', 'URL'], path);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.mkdirSync (node:fs:1007:10)
    at Object.41518 (/usr/home/rtorrent/flood/dist/index.js:2:1228564)
    at __nccwpck_require__ (/usr/home/rtorrent/flood/dist/index.js:2:1622810)
    at Object.73319 (/usr/home/rtorrent/flood/dist/index.js:2:1342284)
    at __nccwpck_require__ (/usr/home/rtorrent/flood/dist/index.js:2:1622810)
    at Object.68335 (/usr/home/rtorrent/flood/dist/index.js:2:1301005)
    at __nccwpck_require__ (/usr/home/rtorrent/flood/dist/index.js:2:1622810)
    at Object.65423 (/usr/home/rtorrent/flood/dist/index.js:2:1278374)
    at __nccwpck_require__ (/usr/home/rtorrent/flood/dist/index.js:2:1622810)
    at Object.6443 (/usr/home/rtorrent/flood/dist/index.js:2:1229065) {
  code: 'ERR_INVALID_ARG_TYPE'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! flood@4.4.1 start: `node --use_strict dist/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the flood@4.4.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-12T15_37_59_127Z-debug.log
```

## Steps to Reproduce

1. Close the master branch from this repo using a FreeBSD OS 
2. Run `npm install`
3. Run `npm build` 
4. Run `npm start`

**Comment by jesec** [comment]
By default, Flood stores its runtime files to `$HOME/.local/share/flood`. 

Make sure that there is a `HOME`.

Otherwise, you may have to specify `--rundir` manually. Run `npm run start -- --help` to know more.

**Comment by fulder** [comment]
Thank you for a fast response @jesec. I do have my HOME set to `/root` but no `.local` folder in there.

I did actually have a leftover `config.js` from the previous abandoned repo (https://github.com/Flood-UI/flood) but removing it didn't seem to have helped the issue.

I've also tried to apply the `--rundir` and run the help command but still getting exactly the same issue in both these cases. Don't know what else I'm missing here.

**Comment by jesec** [comment]
Clean your repo with `git clean -ffdx` or remove it. Then, repeat the build steps. Note that you don't actually have to **build**. You can install from npm registry with `(sudo) npm install --global flood` (or `@jesec/flood` for rolling builds), and then you can simply run `flood`.

Help command does not do anything. It simply prints a useful message that helps you understand CLI arguments. `--rundir` is not a boolean argument. It takes a path, e.g. `--rundir=/home/download/.local/share/flood`.

**Comment by fulder** [comment]
I tried cleaning up everything and it worked just fine to build after that. Must have missed some old build files or configs before, my bad. 

Oh right, I will just use the `npm` registry instead, don't know why I started out with building when it is pushed there now. Thanks! 

I will close this issue again, thank you for your fast help and support @jesec .
