### ISSUE TITLE
Not load with URI = /

### ISSUE THREAD

**Issue by tydoo** [jesec/flood#242]
Type: Bug Report

From the 4.5.0, when i go to "https://site.fr/", flood doent load.

But when i go to "https://site.fr/index.html", flood load et redirect to "https://site.fr/overview".

My systemd Launch : `ExecStart=/usr/bin/env flood --host="0.0.0.0" --baseuri="/" --port=443 --ssl=true --sslkey="/etc/letsencrypt/live/site.fr/privkey.pem" --sslcert="/etc/letsencrypt/live/site.fr/fullchain.pem"`

## Your Environment

- Version used:
  - Version 4.5.0
  - Commit ID Flood 0.0.0-master.d596d4e
- Environment name and version:
  - Node.js version 15.1..0
  - npm version 7.6.3
- Operating system and version: Debian 10
- Torrent client and version: rTorrent 0.9.7

**Comment by jesec** [comment]
No. You don’t need that if you are not serving from a nested route.

**Comment by tydoo** [comment]
I dont understand the response.

On the 4.4.1 version, when i go the "https://site.fr/", flood redirect automaticaly to "/overview" or "/login".

Its not on the new version.

**Comment by jesec** [comment]
Remove `—baseuri` from arguments. It is not needed. There is no notable change in related codes, and I do not expect the behavior to change.

**Comment by tydoo** [comment]
After remvoved, its not works.

**Comment by jesec** [comment]
I just tested and I am not able to reproduce the issue.

Is there any Flood server log about the request? What’s the return code?

What does your browser get? Try F12 and go to network tab.

**Comment by tydoo** [comment]
304.

After cleared the cache, it works.

It came from un-updated JS and CSS files.
