### ISSUE TITLE
Move files goes wrong in v4.5.0

### ISSUE THREAD

**Issue by celogeek** [jesec/flood#246]
Type: Bug Report

- [X] Try to follow the update procedure described in the README and try again before opening this issue.

## Your Environment

- Version used: 4.5.0
- Environment name and version:
  - Node.js version `node --version` : v14.16.0 and v15
  - npm version `npm --version`: 7.6.3
  - Web browser `name and version`: Chrome latest
- Operating system and version: MacOS
- Torrent client and version: 0.9.8

## Summary

Moving several path and files land badly

## Expected Behavior

Each path and file should move to the location properly

## Current Behavior

I've got several files in /data/download/New
I want to move them to /data/download/Movies

Some are direct files like /data/download/New/a.mkv
and other are groups in a directory like /data/download/New/b/a.mkv, /data/download/New/b.mkv ...

So I want to move a.mkv and b to Movies

With node 15, all move to Movies/a.mkv/ all the times
With node 14, it works a bit better, with single file, but directory land badly

Which version of node should works ?

I try 1 by 1, it works only on v14, v15 still has problem.

## Possible Solution

Queue them and process them the same way as 1 by 1
Why torrent location show the group directory instead of the base directory ?
(if I have a torrent "b" in /New which contain several files, so the files is in /New/b/file1 /New/b/file2 ..., I see /New/b as a torrent location instead of /New)

## Steps to Reproduce

1. select single file and directory
2. set torrent location
3. move it else where
4. check that it land properly in the new directory

## Context

Move selection of torrent in another directory

**Comment by celogeek** [comment]
I try moving 2 files (New/a.mkv and New/b.mkv) to Movies
=> it move New to Movies/a.mkv/ !!!!

I move back Movies/a.mkv to New
Then manually move New/a.mkv to Movies, New/b.mkv to Movies,
And run the checksum

This is really problematic.

**Comment by celogeek** [comment]
I try 4.4.1, everything works perfectly.

**Comment by jesec** [comment]
What kind of torrent are you trying to move? Single-file or multi-file?

What do you type in the "Set Torrent Location" modal? What toggles do you check? Note that only directory path is allowed. It is not allowed to rename file of a torrent.

**Comment by celogeek** [comment]
I select several torrents (simple of multi files)

The I set the "Set Torrent Location" modal from "/data/download/New" to "/data/download/Movies"

It move "/data/download/New" -> "/data/download/Movies/first_torrent_selected.mkv/"
It should move each torrent to the new location as in version 4.4.1.

**Comment by jesec** [comment]
So a mix of single-file and multi-file torrents is selected.

**Comment by jesec** [comment]
Apparently the JSON-RPC change breaks XMLRPC response handling. 

https://github.com/jesec/flood/commit/d23404658dbfdf014a4d2039348e65127ad10401

I will fix this. Meanwhile, you can check out my distribution of rTorrent. It has many enhancements.

**Comment by celogeek** [comment]
the issue occur also where I select 2 singles files.

**Comment by jesec** [comment]
Please check out the latest build when it is ready.

**Comment by celogeek** [comment]
Hi,
Sorry for the delay.

I test the master branch.
I can confirm the patch solve the issue.

Thanks

**Comment by sabersalv** [comment]
I also get this one. @jesec Can you publish 4.5.1 docker image? I use `jesec/flood:latest` tag, not `master`

**Comment by jesec** [comment]
> I also get this one. @jesec Can you publish 4.5.1 docker image? I use `jesec/flood:latest` tag, not `master`

I will do it soon.
