### ISSUE TITLE
Dropdown menu is non-functional in Safari 13

### ISSUE THREAD

**Issue by agneevX** [jesec/flood#256]
### Environment

- Version: 4.5.0
- Environment name and version: `Ubuntu 20.04  - arm64`
  - Node.js version: `14.16.0`
  - npm version `6.14.11`
  - Web browser: `Safari 13.1.3`
- Operating system and version: `macOS Catalina`
- Torrent client and version: `qBittorrent 4.3.4.1`

### Summary

Dropdown menu doesn't show in Safari 13. 

### Steps to Reproduce

https://user-images.githubusercontent.com/19761269/112825716-ba09a880-90a9-11eb-8fe9-064d608db220.mov

**Comment by jesec** [comment]
Unable to reproduce on Safari 14.1 or TP 122. 

I am not able to downgrade to an older version of Safari, unfortunately. As such, I have no way to test on an older version of Safari. Additionally, I typically develop and test on Safari TP. Apple's upgrade patterns dictate that it is in the best interest of the community to put more efforts to properly support newer versions. Users are advised to upgrade to the latest version as soon as possible. 

I would accept a PR, but unfortunately, I can't do much about this issue myself.

**Comment by agneevX** [comment]
I understand. Safari 14 has caused me a lot of performance issues so I was forced to go back to version 13.

Is there noticeable lag on scrolling on the TP or on the stable?

**Comment by agneevX** [comment]
It's mostly noticeable on Twitter.com tbh
