### ISSUE TITLE
Tags need a F5 refresh to be displayed after being set

### ISSUE THREAD

**Issue by euri10** [jesec/flood#266]
Type: Bug Report

- [x] Try to follow the update procedure described in the README and try again before opening this issue.

## Your Environment

- Version used:
  - Version (stable release) :  `jesec/flood:4.5.2` docker image
- Torrent client and version: `jesec/rtorrent` docker image

## Summary

when I right click, set a tag on a torrent, it is not displayed, I need to refresh the page with F5 for it to be displayed

## Expected Behavior

I would expect not to be forced to refresh the page

**Comment by jesec** [comment]
It is probably related to the recent enhancements in memoization. I will take a look.

**Comment by jesec** [comment]
Please check the latest build.

**Comment by runaroundhome** [comment]
Fixed, at least for me. I was having the same issue.

**Comment by euri10** [comment]
thanks, works fine !
