### ISSUE TITLE
Torrents with long names get truncated in torrent detail modal

### ISSUE THREAD

**Issue by agneevX** [jesec/flood#273]
Type: Bug Report

- [ ] Try to follow the update procedure described in the README and try again before opening this issue.

## Your Environment

- Version used:
  - Version: 4.5.2
  - Commit ID (development release) `git --no-pager log -1`
- Environment name and version:
  - Node.js version `node --version`
  - npm version `npm --version`
  - Web browser `name and version`
- Operating system and version:
- Torrent client and version:

## Summary

The entire name of the torrent is not visible in the header in torrent detail modal for torrents with long names. 

## Expected Behavior

The entire torrent name should be visible.

**Comment by jesec** [comment]
I will take a look.

BTW: Of course you can use Flood in whatever way you see fit, as long as you comply with the [GPL v3 License](https://github.com/jesec/flood/blob/master/LICENSE), and this message is absolutely not in any way an added term. However, I think it would be beneficial to this project, the community and users themselves that users refrain from publicly posting information that may indicate potential copyright infringement activities. It is recommended to use known free torrents [[1]](https://webtorrent.io/free-torrents) [[2]](https://linuxtracker.org), use `Create Torrent` function to generate test torrents, or simply mask the information.

**Comment by agneevX** [comment]
Thanks, I will remove this image.

**Comment by jesec** [comment]
@agneevX Is this still an issue?

**Comment by agneevX** [comment]
Yes it is, unfortunately.

**Comment by jesec** [comment]
with the latest version?

can you try to upload a screenshot?

**Comment by agneevX** [comment]
Yes, v4.5.3. 

![821EB421-12C1-468F-AE79-72AA6D58755A](https://user-images.githubusercontent.com/19761269/115037664-562a1100-9eec-11eb-84ae-a9067085c32e.png)

**Comment by jesec** [comment]
![image](https://user-images.githubusercontent.com/11585141/115114188-7925f500-9fc0-11eb-93f4-edbc987a0773.png)

I can't reproduce the issue. Please refresh the cache of your browser.

**Comment by agneevX** [comment]
I have, I'm sure its because of the certain way where only the hyphenated portion is brought to the second line `-releaseGroup`.

I've created an example torrent with a blank file, which you can use: https://we.tl/t-NE80oy3mpo

Or you can create a `.torrent` file with the following data and open it:

`
d8:announce0:13:announce-listll0:ee7:comment0:10:created by20:Flood - flood.js.org13:creation datei1618665046e8:encoding5:UTF-84:infod5:filesld6:lengthi0e4:pathl8:test.txteee4:name93:John.Wick.Chapter.3.Parabellum.2019.UHD.BluRay.2160p.TrueHD.Atmos.7.1.DV.HEVC.REMUX-FraMeSToR12:piece lengthi16384e6:pieces0:7:privatei0eee
`

**Comment by jesec** [comment]
It is working perfectly fine for me. F12, select the header element and verify that there is a `overflow-wrap: anywhere` CSS style. 

![image](https://user-images.githubusercontent.com/11585141/115114558-978cf000-9fc2-11eb-96b9-55a6009b069b.png)

**Comment by jesec** [comment]
Please try the latest build.

**Comment by agneevX** [comment]
Yes, that fixes it, thank you.
