### ISSUE TITLE
Web UI broken on ios

### ISSUE THREAD

**Issue by wioo** [jesec/flood#279]
Type: Bug Report

## Your Environment

- Version used:
  - Version (stable release)
v4.5.3
- Environment name and version:
  - Node.js version v15.14.0
  - npm version 7.9.0
  - Web browser: latest safari, brave 1.24(21.4.1.15), firefox 33.0(4119)
- Operating system and version: linux deploy (server), iOS (client)
- Torrent client and version: rtorrent 0.9.8

## Summary

Wont open expected UI

## Expected Behavior

Correct UI

## Current Behavior
![image](https://user-images.githubusercontent.com/8883640/114351411-dc4ffb80-9b6a-11eb-8d34-910e857f416d.png)

## Steps to Reproduce

Try to open web UI on iOS.

## Context

It works on android.

**Comment by jesec** [comment]
I am not able to reproduce on my iOS device, and I don’t think you have the latest iOS version. The latest one looks like this: 

![37A6DA9B-AB81-4341-9752-BFAE98050F74](https://user-images.githubusercontent.com/11585141/114353689-e3ddc780-9b9f-11eb-937b-e5a58084ef3e.jpeg)

Please update your system.

**Comment by wioo** [comment]
Thanks for reply. My system is updated. iOS 12.5.2 is the latest version for my device (6 plus). I think this strated to happen when I changed from flood-git to nodejs-flood (arch aur).

**Comment by jesec** [comment]
Unfortunately, Flood no longer supports Safari that old. 

See https://github.com/jesec/flood/issues/256#issuecomment-809287645 .

**Comment by wioo** [comment]
Got it. What about Brave 1.24(21.4.1.15) and Firefox 33.0(4119)? I can't verify if they are old or not.

**Comment by jesec** [comment]
Anyways, on iOS, there is only one browser. That is Safari. Apple prohibits applications to use their own browser engines, so no matter the name and version, it is still _the Safari_.

**Comment by wioo** [comment]
Oh, good to know. Thanks.
