### ISSUE TITLE
Error while adding one specific torrent

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [jesec/flood#28]
## Your Environment

* Version used: `f731469`
* Environment name and version:
  + Node.js version v14.9.0
  + npm version 6.14.8

Adding a specific torrent file (which I cannot reproduce, but it is a valid file that has worked with rtorrent (rutorrent as ui) in the past.) causes a failure. This only happens with this specific file, adding different torrents with Flood works fine.

## Steps to Reproduce
1. Add the torrent
1. Observe this error in API response:
```json
{"errno":-104,"code":"ECONNRESET","syscall":"write"}
```

Adding the torrent manually (in rTorrent) works fine.

**Comment by jesec** [comment]
`ECONNRESET` is likely temporary connection error.

**Comment by ThatNerdyPikachu** [comment]
It persists even if I try again, restart flood, restart rtorrent, etc.

**Comment by jesec** [comment]
Is that file large? Or have any other unique property? (eg. symbols in torrent or file name, etc.)

**Comment by jesec** [comment]
Flood doesn’t have much logging. You would have to use a debugging console and create breakpoints at relevant points.

**Comment by ThatNerdyPikachu** [comment]
File is 1.53 MB, I've added similar sized torrents with Flood before with no issues.

Filename is plaintext.

```
         Name  [redacted]
Creation Date  2017-10-14 15:10:04 UTC
   Created By  ruTorrent (PHP Class - Adrien Gibrat)
    Info Hash  5e831478fef6bd27206059d84f1600fe6d65b836
 Torrent Size  1.53 MiB
 Content Size  19.63 GiB
      Private  yes
      Tracker  [redacted]
   Piece Size  256 KiB
  Piece Count  80425
   File Count  5
```

**Comment by ThatNerdyPikachu** [comment]
so what can i try to do to resolve this? why would the connection be failing in this one circumstance?

**Comment by ThatNerdyPikachu** [comment]
So, I went through a few things.

The one thing I know is that Flood never sends `load.raw_start` to rtorrent. Every other XMLRPC command that Flood sends is sent, so it's not the connection between rtorrent and flood.

What else could it be then?

**Comment by jesec** [comment]
You may need to create breakpoints at add file function and xmlrpc serialization. That will give you some insights about what went wrong. 

First we need to know whether Flood properly received the file.

**Comment by ThatNerdyPikachu** [comment]
Only thing I'll be able to do easily is `console.log`-esque debugging, since this is a headless box.

So I should print the recieved files on the add-files endpoint, correct?

**Comment by jesec** [comment]
It would be very difficult if you can't do breakpoint debugging. Printing 1.5M raw data to console isn't going to work well. However, you can try to add some simple `console.log`. Try to print out the length (size) of file received in API and payload serialized for xmlrpc.

**Comment by jesec** [comment]
I would recommend you to try to get a local Flood (and tTorrent) instance up and running first for easier debugging.

**Comment by ThatNerdyPikachu** [comment]
It receives file successfully, and constructs a valid SCGI request to send to rTorrent.

However, when trying to send it:
```
Error: write ECONNRESET
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'write'
}
```

:/ 

This is happening in `bufferStream`, and I'm honestly not sure why, Every other request goes through just fine, and this is just as valid as any other request.

**Comment by ThatNerdyPikachu** [comment]
rtorrent xmlrpc logs confirm that it doesn't receive the message.

rtorrent xmlrpc size limit is set at max, so it's not that either...

What else could it be?

**Comment by jesec** [comment]
Interesting. My guess is that Flood sent a malformed XMLRPC message to rTorrent. It is probably rejected. More debugging would be needed to know where exactly things went wrong.

**Comment by ThatNerdyPikachu** [comment]
It looks valid at a glance, to me.

How should I proceed with debugging? (what would be the best thing to do next? dump the xmlrpc body and compare with a working one?)

**Comment by jesec** [comment]
Yeah. You can try to get it to dump the proposed xmlrpc request to a file.

**Comment by ThatNerdyPikachu** [comment]
I'm really curious about why this doesn't work, and why it's only for a specific torrent.

Look forward to finding the cause.

**Comment by ThatNerdyPikachu** [comment]
https://github.com/jesec/flood/blob/master/server/models/client.js#L21-L34

Why is this making a blank request and sending it? Can this be removed?

**Comment by jesec** [comment]
Long time ago Flood was sending `mkdir -p` to rTorrent instead of using JS methods to do file ops itself. It is probably leftovers of some cleanup changes.

**Comment by jesec** [comment]
It can be removed.

**Comment by ThatNerdyPikachu** [comment]
You want me to PR it, or do you want to make the change?

If the latter, I'm pretty sure https://github.com/jesec/flood/blob/e718ff35fc5c28ab6030acd34f8a4881f12d87c8/server/models/ClientRequest.js#L138 can be removed as well, as this parameter is not used anywhere else.

**Comment by jesec** [comment]
Feel free to open a PR. However, I am traveling so I am not able to efficiently develop in the following 5 days. I will see what I can do with my laptop. 

For the `x-filename`, I think we can keep it. Original filename could be an useful detail. We just have to finish the support for it.

**Comment by ThatNerdyPikachu** [comment]
> For the x-filename, I think we can keep it. Original filename could be an useful detail. We just have to finish the support for it.

Noted.

Hopefully I can find some difference in the requests sent, but I find it unlikely based on the code. I just don't see why it would be getting rejected, to be honest.

**Comment by ThatNerdyPikachu** [comment]
Actually,

> original filename could be an useful detail.
Why would someone want to know the original filename of a torrent? i.e. if i imported one from `/home/pika/whatevername.torrent`, and then deleted it, would the original filename really be of much use?

Curious what you think.

**Comment by jesec** [comment]
Some trackers assign numbers to torrents. When a torrent is downloaded, the torrent’s filename is the number. Users might want to know the original filename to know the number so they can easily navigate back to the page of that torrent on tracker site.

**Comment by jesec** [comment]
Ofc the users can also search again for that torrent but it won’t

**Comment by ThatNerdyPikachu** [comment]
@jesec: The requests sent to rTorrent are exactly the same, minus of course `addtime`, `x-filename`, and the actual file buffer.

**Comment by jesec** [comment]
How the file buffer differ? There might be something wrong with serialization.

**Comment by jesec** [comment]
Hi @ThatNerdyPikachu ,

Flood now uses a significantly different way to add torrents. ([96c754d](https://github.com/jesec/flood/commit/96c754ddeb614b45a565e8307c9985ee85bcb7fa)) It saves the torrents first and then adds the torrents to rTorrent using filesystem paths. This method allows the Flood to bypass many potential connection layer problems. 

Could you please check if this issue is still relevant?

**Comment by jesec** [comment]
Hi @ThatNerdyPikachu ,

Any update?

**Comment by ThatNerdyPikachu** [comment]
Hi!

My apologies for taking so long to get to you.
I am currently using ruTorrent, but your changes look like it will fix the issue at hand.
I will test when I can and reopen this issue if needed.

Thank you!

**Comment by GitHubGeek** [comment]
I've come across a couple of .torrent files that would add through the watchdir, but not through Flood upload.

Running version 999463dfb212e023d584ccae730ca02507c99afb

.torrent files in question are big (800KB - 1MB), have files with very long names / path names

**Comment by jesec** [comment]
> I've come across a couple of .torrent files that would add through the watchdir, but not through Flood upload.
> 
> Running version [999463d](https://github.com/jesec/flood/commit/999463dfb212e023d584ccae730ca02507c99afb)
> 
> .torrent files in question are big (800KB - 1MB), have files with very long names / path names

I need more details. Does Flood server provide any log? Can you successfully add other torrents? 

If possible, can you send me the torrent in question?
