### ISSUE TITLE
Flood fails to start with option `--auth none`

### ISSUE THREAD

**Issue by brianredbeard** [jesec/flood#289]
## Your Environment

started from Linux container `jesec/flood`

```bash
1c51575ed3e7:/$ flood --version
4.5.3
1c51575ed3e7:/$ cat /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.11.10
PRETTY_NAME="Alpine Linux v3.11"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```

## Summary

As mentioned in the title and demonstrated under "current behavior",  flood presently refuses to start when instantiated with the flag `--auth none`.

## Expected Behavior

Flood should start

## Current Behavior

Flood refuses to start

```bash
1c51575ed3e7:/$ find /config/
/config/
/config/.ash_history
1c51575ed3e7:/$ flood --auth none 
Invalid configuration: 1 validation issue(s)

  Issue #0: custom_error at configUser
  Empty client connection settings.
```

## Steps to Reproduce

1. Run container `jesec/flood` with option `--auth none`
2. Check the logs to stdout/stderr

**Comment by jesec** [comment]
`Empty client connection settings.`

Flood needs to know how to connect to your torrent client. `flood —help` to see available arguments.

**Comment by brianredbeard** [comment]
I'll go ahead and close this out, but chalk it up to ambiguity in the error message.

**Comment by crisclacerda** [comment]
I am having trouble with this.
Trying to start flood with
`./flood-linux-arm64 --auth none --qburl 127.0.0.1:8080 --qbuser admin --qbpass adminadmin -h 0.0.0.0.0`

But got this error:
https://pastebin.com/Aq26hCTa

**Comment by jesec** [comment]
- qburl: It is not a (full) URL. 
- h: 0.0.0.0.0 is not a valid IP address.
