### ISSUE TITLE
npm registry not found

### ISSUE THREAD

**Issue by brezinajn** [jesec/flood#31]
Type: Bug Report

## Your Environment

* Version used: latest
* Environment name and version:
npm: 6.13.4
* Operating System and version:
Ubuntu 20.04
## Summary
`npx @jesec/flood --help` ends with

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@jesec%2fflood - Not found
npm ERR! 404  '@jesec/flood@latest' is not in the npm registry.
```

**Comment by jesec** [comment]
It has been moved to `flood` (unscoped). 

npmjs.com/flood

**Comment by brezinajn** [comment]
👍 Great. Thanks.
