### ISSUE TITLE
Total Upload/Download stat reset at every rtorrent restart

### ISSUE THREAD

**Issue by ThomasLachaux** [jesec/flood#313]
Type: Bug Report

- [x] Try to follow the update procedure described in the README and try again before opening this issue.

## Your Environment

- Version used:
  - Version (stable release) 4.5.4
  - Commit ID (development release) `git --no-pager log -1` abf99ba52be3250403147d3d78d1249bce8bcd2c
- Environment name and version:
  - Node.js version `node --version`  v16.1.0
  - npm version `npm --version` 7.11.2
  - Web browser `name and version` Chrome 90.0.4430.212
- Operating system and version: Windows 10 2009 
- Torrent client and version: rtorrent 0.9.8-jc+1620316646-3e0dbaf

.rtorrent.rc
```
scgi_local = /tmp/rtorrent.sock

encoding_list = UTF-8
port_range = 49184-49184
port_random = no
check_hash = no
directory = /data/torrents
session = /data/.session
encryption = allow_incoming, try_outgoing, enable_retry
trackers.use_udp.set = yes
dht.mode.set = off
protocol.pex.set = no

min_peers = 1
max_peers = 100
min_peers_seed = 1
max_peers_seed = 50
max_uploads = 15

network.xmlrpc.size_limit.set = 10000000
```

## Summary
The total Upload/Download stat resets at every restart of rtorrent. Does anybody has this problem ?

## Expected Behavior
The total upload/download stats should remain even if rtorrent is restarted

## Steps to Reproduce
- Launch rtorrent and flood.
- Kill rtorrent and restart it
- Flood displays now 0/0 in the up/down stats

## Context
I am using this image https://github.com/Wonderfall/docker-rtorrent-flood but I also tried it in a clean server without docker. Rtorrent installed with apt and flood from source.

**Comment by jesec** [comment]
This is expected behavior. The stat is per-session.

**Comment by ThomasLachaux** [comment]
Hey ! Thank you for your answer. Too bad it is an expected behavior. Do you know if there is a way to tweak it ?

**Comment by jesec** [comment]
Flood fetches the stats from rTorrent directly. Unfortunately I don't think there is anything to tweak.

**Comment by ThomasLachaux** [comment]
Ok thanks, at least I tried 😃
