### ISSUE TITLE
Cannot start the frontend development server, eslint import/order error

### ISSUE THREAD

**Issue by sabersalv** [jesec/flood#315]
Type: Bug Report

## Your Environment

master branch

## Summary

![image](https://user-images.githubusercontent.com/2525544/119435329-7d29fd00-bd4c-11eb-8e3d-52e42de46493.png)

## Steps to Reproduce

```
  npm run start:development:client
```

**Comment by sabersalv** [comment]
Also get this one, I'm using `http://localhost:4200`

![image](https://user-images.githubusercontent.com/2525544/119438953-e4977b00-bd53-11eb-8f29-1badc975af24.png)

**Comment by jesec** [comment]
ESLint ones are not really errors. The rules are there to help developers to write better codes. I guess the recent dependency bump brings some changes to the ruleset. I have fixed them in 7f1188d98a8fc4bfc63d95beebba6c0969b65d79. 

The `DOMException` is definitely an issue. I haven't touched related parts recently, though. Maybe the recent dependency bump brings some undesired behavior changes.

**Comment by sabersalv** [comment]
> ESLint ones are not really errors. The rules are there to help developers to write better codes.

Maybe set that rule to `warning` instead of `error`.

Just to confirm, do you have these errors when you're doing the development on your local machine?

**Comment by jesec** [comment]
Recent changes don't touch frontend, so I just `npm build` and use `development:server` only.

 Anyways, it should be working now.

**Comment by sabersalv** [comment]
It's working. Thanks
