### ISSUE TITLE
Empty folder left after removing torrent (delete data)

### ISSUE THREAD

**Issue by gboudreau** [jesec/flood#35]
Type: Bug Report

## Your Environment
* Version used:
  + Commit ID (development release) `ee0257a557a7bedf4110dcbb50bda2207494b81d`

## Summary
When removing (and deleting data) a torrent that has 1+ file(s) inside a folder, the folder is left empty. It should be deleted.

## Possible Solution
When deleting data, Flood should check if the torrent contains files inside a folder, and if so, check if that folder is empty, after deleting all files, and if so, it should deleted the folder too.

## Steps to Reproduce
1. Download a torrent that includes 1+ files inside a folder
2. Remove that torrent
3. Check the checkbox to `Delete data`
4. Check that the file(s) were deleted, but an empty folder is left

**Comment by gboudreau** [comment]
I think it should already try to delete the folder (recursively):
https://github.com/jesec/flood/blob/916f2e51e82217c81a14c0be60da8b9e618aaf74/server/services/clientGatewayService.js#L106-L107
Maybe `filesToDelete` doesn't contain the folder, but only files inside it..?
I guess one would have to check what is returned by `d.directory_base` and `fileListMethodCallConfig.methodCalls`, to understand how a torrent with a file differs from a torrent with a file inside a folder.

**Comment by jesec** [comment]
See #13 and #25.

**Comment by gboudreau** [comment]
Thanks for the pointers. Didn't see those somehow...
I'll still try my hand at implementing a fix; probably something along the lines of tracking when a new base_dir gets created by Flood (or rTorrent?) for an added/moved torrent, and deleting an empty directory only if that flag is set.
Might not be solid enough to be merged as-is, but should be good enough for my use-case.

**Comment by gboudreau** [comment]
In fact, since any fix I would implement would very probably end up being for me only, I'll skip the dev environment setup & learn Node parts, and just implement what I need in a shell script.
Let's close this issue.
