### ISSUE TITLE
Deprecated Dependency [http_parser]

### ISSUE THREAD

**Issue by CodyRWhite** [jesec/flood#359]
Type: Bug Report

- [ x ] Try to follow the update procedure described in the README and try again before opening this issue.

## Your Environment

- Version used:
  - Version 4.6.1
- Environment name and version:
  - Node.js version `node --version` v16.4.1
  - npm version `npm --version` 7.19.1
  - Web browser `name and version` N/A
- Operating system and version: RockyLinux 8.4
- Torrent client and version: rTorrent - Latest

## Summary

After installing flood and running on the latest version I am seeing deprecation warnings. 

## Current Behavior
```
[rtorrent@SERVER-001 ~]$ flood -h 0.0.0.0
Flood server 4.6.1 starting on http://0.0.0.0:3000

(node:12027) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

## Steps to Reproduce

```
### install Flood
dnf install nodejs -y

su rtorrent 
cd /home/rtorrent
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

nvm install node
npm install -g npm
npm install -g flood

flood -h 0.0.0.0
```

**Comment by jesec** [comment]
I am working on it: https://github.com/jesec/flood/projects/6#card-59708842, #327 .

**Comment by CodyRWhite** [comment]
Sorry I tried looking there first, but I was not able to find an exact reference to the update.

**Comment by raaron773** [comment]
I fresh installed qbittorrent and flood and I am getting this error. Is there a way to use flood by bypassing this error somehow?
I am on RaspbianOS armhf.

**Comment by jesec** [comment]
This is a warning. It does not indicate any defective behavior. 

If you are not able to connect, you have to take a look at something else. Are you sure that you exposed Flood to other machines in your network (often done with `--host 0.0.0.0`)?

**Comment by raaron773** [comment]
Sorry, I am noob I don't know what you mean or how to use `--host 0.0.0.0` 
Been trying to get this to work for quite some time now and don't know what else to do

**Comment by jesec** [comment]
It is a command line argument. If you was running Flood with `flood`, run it with `flood --host 0.0.0.0`.

**Comment by raaron773** [comment]
Like this?
https://pastebin.com/sTtrcu3R

**Comment by jesec** [comment]
If you use Docker, you don't need `--host 0.0.0.0`. 

Instead, expose the service to your LAN with Docker options. For instance, in your compose file: 

```
    ports:
      - 0.0.0.0:3001:3001
```

**Comment by raaron773** [comment]
oh man! I have been trying to get this to work for a really long time!

Thank you very much!! I really appreciate your help for this!! I finally got it to work!! yay!!

**Comment by trim21** [comment]
should be fixed
