### ISSUE TITLE
Flood does not load with ssl enabled

### ISSUE THREAD

**Issue by j3ws3r** [jesec/flood#362]
Type: Bug Report

- Version used:
  - Flood 4.6.0
- Environment name and version:
  - Node.js version `node v16.4.0`
  - npm version `npm 7.18.1`
  - Web browser `Safari 14.0.3, Chrome 91.0.4472.114 `
- Operating system and version: Server - Ubuntu 20.04.2 LTS
- Torrent client and version:
  Transmission torrent client
## Summary

Installed flood through npm, made it as a service in systemd/system. As http it runs completely fine. Then I tried to setup https access to flood. To test the waters out I ran `sudo flood --host 192.168.1.139 --port 3003 --ssl=true --sslkey="/home/karolis/.local/share/flood/key.pem" --sslcert="/home/karolis/.local/share/flood/fullchain.pem"
`
flood launched, but when I access it, it fetches some requests, but page is empty.

## Expected Behavior

Full functionality of flood interface

## Current Behavior

-

## Steps to Reproduce

1. Install flood from npm
2. Add ssl certificates to .local/share/flood
3. launch flood with command "flood --ssl --host 192.168.1.139" (host should be accessible for other lan devices).
4. Access web of flood.

It is either stuck on background colour or this view
<img width="693" alt="image" src="https://user-images.githubusercontent.com/51436874/124826545-9e9e1b80-df7d-11eb-92bb-f430a92c820d.png">
And this is the output of active flood: 
<img width="542" alt="image" src="https://user-images.githubusercontent.com/51436874/124826263-4e26be00-df7d-11eb-8066-e924fbfc35a9.png">

**Comment by CodyRWhite** [comment]
I would try and update that to --host 0.0.0.0

When I was running it with 127.0.0.1 I was only able to see it locally. 0.0.0.0 will be browsable on all interfaces so if your DHCP changes it will adjust (if your not using static :D ) 

Also make sure you have your firewall open for incoming connection on 3000 

I usually work on RHEL but you can try this command 

```
firewall-cmd --zone=public --permanent --add-port=3000/tcp
firewall-cmd --reload
```

**Comment by CodyRWhite** [comment]
Also you missed a obfuscation on your image under the request section. In case you want to correct that.

**Comment by j3ws3r** [comment]
> I would try and update that to --host 0.0.0.0
> 
> When I was running it with 127.0.0.1 I was only able to see it locally. 0.0.0.0 will be browsable on all interfaces so if your DHCP changes it will adjust (if your not using static :D )
> 
> Also make sure you have your firewall open for incoming connection on 3000
> 
> I usually work on RHEL but you can try this command
> 
> ```
> firewall-cmd --zone=public --permanent --add-port=3000/tcp
> firewall-cmd --reload
> ```

For running - it works completely fine in http:// , I can run it just fine with everything working. I have assigned static ip to this machine, so I use 192.168.1.139, but thanks, I for better usage I set up 0.0.0.0, as I have two network interfaces, although I use only one.

As I mentioned in the report before, I use ubuntu 20.04LTS (ubuntu server) headless. I disabled firewall completely (ufw status is inactive), so no matter what port it should be forwarded regardless: 
![image](https://user-images.githubusercontent.com/51436874/124886741-38e17c00-dfdd-11eb-9c8e-c583b1b898ef.png)

**Comment by j3ws3r** [comment]
So ok, I wiped npm flood completely and tried to add it through apt. 
I added source: `echo "deb [trusted=yes] https://deb.jesec.io/ devel main" | sudo tee /etc/apt/sources.list.d/jesec.list
`
Then I edited path to flood in systemd/system/flood.service which I created and also added arguments.
It seems that it worked. Still it is a mystery why I was not able to achieve the same from npm.
