### ISSUE TITLE
rtorrent: torrents added outside of Flood report a bogus "Added" date

### ISSUE THREAD

**Issue by falzm** [jesec/flood#368]
Type: Bug Report

## Your Environment

- Version used:
  - Version (stable release) : 4.6.1 (via Docker image `jesec/flood:latest` sha256:95dd5112471e3afcb85b1760026d9b6370540bb2a238e22b094236d74afb67e0)
- Operating system and version: Linux (Docker container)
- Torrent client and version: rtorrent 0.9.8 (from Alpine Linux)

## Summary

The Flood UI reports an incorrect *Added* date for torrents added outside of its control.

## Expected Behavior

The Flood UI should display the torrent add/load date reported by the torrent client (here, rtorrent). 

## Current Behavior

* When adding a torrent via the Flood UI, the *Added* date is correctly set.
* When load new torrents outside of Flood (e.g. using rtorrent's watch system), the torrent *Added* date reported by Flood is bogus (01/01/1970, or *None* when looking in a torrent's details section). I've checked the result of rtorrent's `d.load_date` XML-RPC method, it correctly returns the UNIX timestamp of the time a torrent is loaded.

## Possible Solution

I haven't looked at how Flood retrieves the torrent add date, however the correct way to get this information from rtorrent seems to be via the `d.load_date` XML-RPC method.

## Steps to Reproduce

1. Set up an rtorrent/Flood combination
2. Load a torrent directly in rtorrent
3. Check the *Added* time reported in the Flood UI

Thank you 🤞

**Comment by jesec** [comment]
Unfortunately rTorrent does not record the added date of a torrent. You must add the torrent through Flood if you wish to have the proper added date.

**Comment by falzm** [comment]
@jesec it does, as I mentioned in the issue: the rtorrent `d.load_date` XML-RPC command returns a UNIX timestamp of the added date.

**Comment by jesec** [comment]
No it is not. It is the date when a torrent was loaded to the session. That means it might be the date when rTorrent was launched.

**Comment by falzm** [comment]
> No it is not. It is the date when a torrent was loaded to the session. That means it might be the date when rTorrent was launched.

Ah you're right, indeed the load date gets updated once rtorrent restarts and re-loads all torrents... Well, I guess I'll have to add torrents via Flood's API then, since my work flow requires headless adding of torrents. 😔

**Comment by toscompliantname** [comment]
uwu what's this
https://github.com/rakshasa/rtorrent/issues/1054
>Never mind. I realised that RuTorrent sends a request with a key value of "cmd" and "d.custom=addtime". Combined with the key value of "mode" and "list", it adds an extra string onto the array of the torrent hash in the response that is the added datetime. All I needed to do was multiply this by 1000 and then parse it as a DateTime which then matched what the web interface displayed.

**Comment by NoLooseEnds** [comment]
Following. Currently getting my torrents via Flexget and watchfolders.

**Comment by falzm** [comment]
> uwu what's this
> [rakshasa/rtorrent#1054](https://github.com/rakshasa/rtorrent/issues/1054)

@jesec is this something you could work with?

**Comment by ConquerorDopy** [comment]
Flood already supports this, it just needs to be configured in rTorrent. See https://github.com/Flood-UI/flood/issues/135#issuecomment-250058419.

```
system.method.set_key = event.download.inserted_new, loaded_time, "d.custom.set=addtime,$cat=$system.time=;d.save_full_session="
```

**Comment by jesec** [comment]
> > uwu what's this
> > [rakshasa/rtorrent#1054](https://github.com/rakshasa/rtorrent/issues/1054)
> 
> @jesec is this something you could work with?

No. That issue is totally irrelevant.

**Comment by NoLooseEnds** [comment]
Can confirm that adding
```
method.set_key = event.download.inserted_new, loaded_time, "d.custom.set=addtime,$cat=$system.time=;d.save_full_session="
```
to .rtorrent.rc worked. Torrents added to watch folders now get the correct date.

**Comment by falzm** [comment]
Thanks @NoLooseEnds, then that workaround will be fine for me.
