### ISSUE TITLE
add a large torrent result in EPIPE error

### ISSUE THREAD

**Issue by sabersalv** [jesec/flood#376]
Type: Bug Report

- [x] Try to follow the update procedure described in the README and try again before opening this issue.

## Your Environment

- Version used: v4.6.1
  - Version (stable release)
  - Commit ID (development release) `git --no-pager log -1`
- Environment name and version:
  - Node.js version `node --version`: v14.16.1
  - npm version `npm --version`: 6.14.12
  - Web browser `name and version`: Firefox 89
- Operating system and version: macOS / Linux
- Torrent client and version: rtorrent 0.9.8 XML rpc

## Summary

Looks like there's a problem to add a torrent by file larger than 1.6 MB

## Expected Behavior

Add torrent successfully

## Current Behavior

Add torrent failed

## Possible Solution

I now use rtorrent's watch directory feature to add these large torrents, and use chtor for fast resume.

## Steps to Reproduce

1. Find a torrent file larger than 1.6 MB
2. Add Torrent by file
3. Returns failed to add torrent
4. Check Devtool network tab -> { code: 'EPIPE', message: 'write EPIPE' }

**Comment by jesec** [comment]
I am not able to reproduce the issue. 

I just tried to add a large torrent, and it succeeds:

![image](https://user-images.githubusercontent.com/11585141/126023825-b5996cc9-3be5-4ecc-8a3d-2bbe2a9b7252.png)

![image](https://user-images.githubusercontent.com/11585141/126023865-045eee6a-1f1e-49d2-b9aa-e52047d4e44a.png)

**Comment by sabersalv** [comment]
[a.zip](https://github.com/jesec/flood/files/6834129/a.zip)

Can you try this torrent file? I've removed the tracker url.

**Comment by mirolm** [comment]
Have you configured "network.xmlrpc.size_limit.set" in your .rtorrent.rc file? I remember the default value was quite small and was limiting the size of objects you can pass through XMLRPC.

Try to set it to 16 or 32 megs and check if this helps.

network.xmlrpc.size_limit.set = 16M

**Comment by sabersalv** [comment]
@mirolm Thanks for the solution, it didn't work.

I tried `jesec/rtorrent` (jsonrpc), works fine, so I guess it related to xlmrpc.  If I recall correctly, I saw it somewhere there're problems with xmlrpc, flood use directory to add torrent instead of xlmrpc to save a lot of troubles, but I cann't find it now.

I'll try to create a reproduce-able docker compose file.

**Comment by jesec** [comment]
XMLRPC is known to have problems.

Since the switch to JSON-RPC, Flood no longer adds the torrent by local path (in order to avoid circular file access dependency, which users frequently complained about). Instead, it directly adds the torrent via socket. 

https://github.com/jesec/flood/commit/1058f0a16d0d51e8ecdd2aa4fe995b5fb9bb1d65

XMLRPC users are invited to switch to JSONRPC. No other action can be taken here.

**Comment by sabersalv** [comment]
That's it then, I'll switch to JSONRPC. Thanks for the help.
