### ISSUE TITLE
Please add examples for the CLI tool

### ISSUE THREAD

**Issue by flying-sausages** [jesec/flood#38]
Type: Documentation Issue

## Summary
It would be nice to see what the CLI tool can offer without having to install flood first. I'm wondering whether to migrate to this fork but I'd like to automate user creation and password changing through scripts for example, so this would be nice to see.

**Comment by jesec** [comment]
Run `flood --help`, `npx flood --help` or `npm run start -- --help` to get help about command line arguments.

If you want to know more about configurations, check `config.template.js`. Command line interface made everything in `config.js` configurable via command line. 

Unfortunately, currently command line interface does not provide more capability than what was defined in ``config.template.js`. Specifically, it can NOT manipulate database to create user or change password of a user. 

However, you will be able to do that by calling [APIs](https://github.com/jesec/flood/blob/master/server/routes/api.js) directly. It is simple JSON.

**Comment by flying-sausages** [comment]
The one use case i could think of is seedbox providers setting up environments for their clients, and user administration would be a large part of that. I'm wondering if the CLI tool could function as a wrapper for this API with sanitisation etc.

**Comment by jesec** [comment]
Main CLI is designed as an "entry point" for Flood (Flood is launched by it). It would be inappropriate to incorporate such features into this interface. 

We would need to create a separate CLI tool for such purposes. It can be named "floodctl" for example. 

I don't think such tool would be necessary, though. You can just call Flood's API (for instance, POST a JSON object with credentials to http://127.0.0.1:3000/auth/register will create a user) via any HTTP client (eg. `curl`).

**Comment by jesec** [comment]
Hi, @flying-sausages ,

I believe your question is already answered. Could you please close this issue if there is no further question?
