### ISSUE TITLE
Add hover hint to menu button

### ISSUE THREAD

**Issue by mirolm** [jesec/flood#41]
Type: Feature Request

- [x] If you want to contribute to the project please review the [contributing guidelines](https://github.com/Flood-UI/flood/blob/master/.github/CONTRIBUTING.md).

## Summary

All other buttons as "add torrent", "stop torrent" and so on have description/hint when you go over them with mouse. The menu button can have short description like "Collapse menu" or something like that.

## Idea of implementation

None.

**Comment by jesec** [comment]
I did that intentionally.

It is not really necessary and can be confusing. It is “Collapse menu” when menu is expanded but it becomes “expand menu” when menu is collapsed. The main problem is that it is mainly used by touch screen devices and all kinds of hover hints don’t work well on touch screen and it is even worse when hint is changing (expand <-> collapse). The hint can linger there with incorrect text displayed.

**Comment by mirolm** [comment]
I see thanks for the reply.
