### ISSUE TITLE
Flood does not properly set various settings in Transmission from the settings page.

### ISSUE THREAD

**Issue by andrew-kennedy** [jesec/flood#416]
I noticed flood sets many values to 0 no matter what they are set to in the UI, why is this the case? It makes it hard to know what values will have any effect and it's tough to map them to transmission settings, for example global upload slots enables seed queue when it's nonzero and also sets the seed queue size, and disables when zero, which is very non-intuitive compared to other transmission UIs which have a toggle box. There's also no way to set or toggle alt-speed.

https://github.com/jesec/flood/blob/8c04bf245cf5482bcbd2cb2ce8d7f3ea5edde401/server/services/Transmission/clientGatewayService.ts#L471

**Comment by trim21** [comment]
fixed
