### ISSUE TITLE
Disk usage broken in docker?

### ISSUE THREAD

**Issue by runaroundhome** [jesec/flood#43]
I'm using the latest docker image `jesec/flood:master`, but can't seem to get the disk usage to work.
Is there some setup required for docker users?
![image](https://user-images.githubusercontent.com/16973228/94633553-276e9380-032a-11eb-85b8-6577417b0257.png)

It works with the jfurrow build, just not this one.

**Comment by jesec** [comment]
There has to be a mounted regular file system for the disk usage function to work. How you manage data sharing between host and container? 

Commit https://github.com/jesec/flood/commit/ee83e8f3aab7f7f4d8aa87cb04eef3b0eee8fd79 ignored `tmpfs` and `squashfs` fs types. You can try to revert the change and see if things work for you. 

I didn’t notice this problem when I test the Docker image. Can you run an interactive shell into your container and send me the output of “df” command?

**Comment by runaroundhome** [comment]
Hmm, I'm not using tmpfs or squashfs, so that shouldn't cause the issue for me.

Seems it comes through as my raid array, as well as overlay.

Here is `df`:
![image](https://user-images.githubusercontent.com/16973228/94652278-3c611c00-0356-11eb-8f3f-d9d94c4929fb.png)

**Comment by jesec** [comment]
Try `df -xsquashfs -xtmpfs -xdevtmpfs`. That’s the command used by Flood to get disk usage on Linux currently.

**Comment by runaroundhome** [comment]
Hmmm, seems maybe the wrong version of df in the docker image?
![image](https://user-images.githubusercontent.com/16973228/94654790-0c1b7c80-035a-11eb-8ae2-9d1bbcf5c996.png)

**Comment by jesec** [comment]
I will take a look at this.

**Comment by runaroundhome** [comment]
Now works, thanks!
