### ISSUE TITLE
Torrent Comments Missing from Torrent Details in Flood GUI

### ISSUE THREAD

**Issue by albino1** [jesec/flood#435]
## Your Environment

`flood-linux-x64 4.7.0` with `rtorrent 0.9.8`

## Summary

I noticed that Flood doesn't display the Torrent Comment from the actual .torrent file anywhere in the interface.  As an easy example where this can be important, many of the top trackers include the URL to the individual torrent page, which can very useful, however they're not visible in Flood.  As an example here are the same torrents in ruTorrent and Flood:

![rutorrent](https://user-images.githubusercontent.com/12164957/137816982-73d17da0-7a9a-4bad-8847-c19087dd9db9.jpg)

![flood](https://user-images.githubusercontent.com/12164957/137816995-165188b9-0b91-48ae-8c88-d0090e619728.jpg)

Also of note is that in ruTorrent the URL is clickable allowing you to return to the tracker torrent page in one click.

## Expected Behavior

Flood should show the Torrent Comment, and if a URL, make it clickable.

## Current Behavior

The Torrent Comment is not displayed anywhere in the interface.

## Steps to Reproduce

1. Add a .torrent file which contains a comment.
2. Open the details in Flood and see that there is no comment listed.

Thanks.

**Comment by zotabee** [comment]
Would love to see that aswell!

**Comment by FinalDoom** [comment]
Working on this now
