### ISSUE TITLE
Folder destination doesn't apply

### ISSUE THREAD

**Issue by zotabee** [jesec/flood#459]
Type: Bug Report

## Your Environment

- Version used:
  - Version (stable release) : Flood 4.7.0 via jesec/flood:latest
- Environment name and version: Docker + Ansible
- Operating system and version: Debian 11 (Bullseye) (64-bit)
- Torrent client and version: qBittorrent v4.3.9 (64-bit) via ghcr.io/linuxserver/qbittorrent

## Summary

"Destination" path is not correctly applied, it goes to the root of the mounted data folder from the container.

If I add a movie torrent and I choose "Destination" : /downloads/movies/

MyMovie/MyMovie.mkv or MyMovie.mkv doesn't end there.

## Expected Behavior

![Screenshot 2021-12-06 185947](https://user-images.githubusercontent.com/89345101/145227820-c42eccfe-ba31-4d02-837f-10e3a48fdf83.png)

It should end to /downloads/movies/MyMovie/MyMovie.mkv or /downloads/movies/MyMovie.mkv

## Current Behavior

It ends in /downloads/MyMovie/MyMovie.mkv or /downloads/MyMovie.mkv

![Screenshot 2021-12-08 153056](https://user-images.githubusercontent.com/89345101/145227845-ab443cf3-e25f-45a7-adc5-0a58c7f5f857.png)

It ends in the red spots instead of the subfolders for each category/tags that you can see in this example pic:

![Screenshot 2021-12-08 153523](https://user-images.githubusercontent.com/89345101/145229949-f45c52f9-726e-4a8e-9384-e985789d1c26.png)

## Possible Solution

- Flood issue ? Everything else works fine with Flood.

- qBittorrent issue ? It works when doing the same through qBittorrent Web UI.

- Dockerized env issue ? Everything else work

## Steps to Reproduce

1. Open Flood
2. Click on the "+" button
3. Point to a .torrent or multiple .torrent files
4. Point to a Destination
5. Confirm and add the Torrent

## Context

Note 1 : Tags work, they are applied ✔️
Note 2 : Flood correctly list all the subfolders when clicking on the "loop" button and show correctly the arborescence. ✔️
Note 3 : "Suggest destination based on selected tag" feature works ✔️

Docker compose files via Ansible tasks : 

filetree : https://github.com/Pro-Tweaker/SEEDbox/blob/main/roles/filetree/tasks/main.yml
flood : https://github.com/Pro-Tweaker/SEEDbox/blob/main/roles/flood/tasks/main.yml
qbittorrent : https://github.com/Pro-Tweaker/SEEDbox/blob/main/roles/qbittorrent/tasks/main.yml

**Comment by l4kr** [comment]
Found the culprit!!!

In qBittorrent Settings>Downloads, change Default Torrent Management Mode to Manual.

It will now work properly.

**Comment by zotabee** [comment]
I confirm, I changed it back to Manual and now it works ! Thank you so much @l4kr for your finding !
