### ISSUE TITLE
remove old flood version for clean install

### ISSUE THREAD

**Issue by spolen88** [jesec/flood#47]
Type: Question

## Question
How would I completely remove a manual install of flood, made from the jfurrow git to do a clean install from here?

EDIT: I assume the only thing I need to do is delete the flood directory, but I don't like to assume.

**Comment by jesec** [comment]
Older Flood versions don’t have the capability to be installed system-wide and no file is stored to other directories. Simply delete the folder and that’s it.

**Comment by spolen88** [comment]
Thanks for the info and quick response.
