### ISSUE TITLE
FATAL internal error

### ISSUE THREAD

**Issue by shinas101** [jesec/flood#532]
$ flood

Flood server 4.7.0 starting on http://127.0.0.1:3000

(node:35064) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
[Axios v4.7.0] Transitional option 'clarifyTimeoutError' has been deprecated since v1.0.0 and will be removed in the near future
[Axios v4.7.0] Transitional option 'forcedJSONParsing' has been deprecated since v1.0.0 and will be removed in the near future
[Axios v4.7.0] Transitional option 'silentJSONParsing' has been deprecated since v1.0.0 and will be removed in the near future
FATAL internal error. Please open an issue.
Unhandled rejection: undefined

**NOTE:** works perfectly with sudo with 
" (node:35064) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created) "
with this error

on running `node --trace-deprecation ...` it gives
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Node.js v17.7.2

**SYS INFO:**
os: archcraft 
shell: zsh
npm-version : 8.5.5
node-version : v17.7.2
browser : chrome (latest)

**TRIED:** reinstalling / updating axios ,http-parser

if you need more info please ask ,
btw awsome project loved it

**Comment by sunbart** [comment]
Getting a very similar error, trying to run the `jesec/flood` docker image

    >> docker run -it jesec/flood --auth none --dehost host --deport 12345 --deuser user --depass pass
    
    Flood server 4.7.0 starting on http://0.0.0.0:3000
    
    Starting without builtin authentication
    
    (node:8) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
    (Use `node --trace-deprecation ...` to show where the warning was created)
    FATAL internal error. Please open an issue.
    Unhandled rejection: undefined

(I'm aware I'm missing other configs like volumes and ports btw 🙂)

**Comment by binamov** [comment]
I got the same issue, container keep restarting. I tried the tips from #359 but didn't help.

**Comment by binamov** [comment]
Switched my docker pulls from `latest` to `master` , fixes the issue

**Comment by shinas101** [comment]
> Switched my docker pulls from `latest` to `master` , fixes the issue

Can you please share the command you used ?

**Comment by jesec** [comment]
I will do a new release soon.

**Comment by sunbart** [comment]
I only got to testing this now (sorry), but switching to `master` didn't help.

Here's my updated command, more fleshed out now.

```
docker run \
    -it --rm \
    --name flood \
    -p 3001:3001 \
    -v /path/to/downloads:/downloads \
    -v /path/to/config:/config \
    -e HOME=/config \
    -u 1000:1000 \
    jesec/flood:master \
        --port 3001 \
        --auth none \
        --dehost host \
        --deport port \
        --deuser user \
        --depass pass \
        --allowedpath /downloads
```

The output:

```
Flood server 0.0.0-master.5a9f701 starting on http://0.0.0.0:3001

Starting without builtin authentication

(node:7) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
FATAL internal error. Please open an issue.
Unhandled rejection: undefined
```

You can see it's on the latest commit (5a9f701), but the error has not changed.
