### ISSUE TITLE
Not working in read_only docker container

### ISSUE THREAD

**Issue by ojio-san** [jesec/flood#54]
Type: Bug Report

- [ ] Try to follow the update procedure described in the README and try again before opening this issue.
- [x] Please check the [F.A.Q.](https://github.com/Flood-UI/flood/wiki/F.A.Q.).
- [x] Please check the [Troubleshooting](https://github.com/Flood-UI/flood/wiki/Troubleshooting) wiki section.

## Your Environment

* Version used:
  + Version (stable release) `master branch`
  + Commit ID (development release) `d17e3fee08a0f262e8a529347e2bccf3063371e7`
* Environment name and version:
  + Node.js version `node-lts 12.19.0 (same with node 14.13)`
  + npm version `6.14.8`
  + Web browser `Firefox 81`
* Operating System and docker version:
  + Running on `Debian 10.6 stable` with `Docker version 18.09.1, build 4c52b90` [https://packages.debian.org/buster/docker.io](https://packages.debian.org/buster/docker.io)
  + Running with `docker-compose 1.21.0-3` [https://packages.debian.org/buster/docker-compose](https://packages.debian.org/buster/docker-compose)
  + Revelant docker-compose.yml : [https://pastebin.com/raw/pLWtxE3j](https://pastebin.com/raw/pLWtxE3j)

## Summary
Container not starting with `read_only: true` with error `Failed to access runtime directory` (debug log is [here](https://pastebin.com/raw/1S4k0NBd))
I'm using NODE_DEBUG=timer,http,net,fs,cluster,tls,stream,child_process,module to get this log.

## Expected Behavior
To work fine with or without `read_only: true`.
Without this, it's okay (debug log is [here](https://pastebin.com/raw/bJeGswvj))

## Possible Solution

Not a single clue, but it was working with read_only with forked version from Flood-UI/flood

## Steps to Reproduce

1. use docker
2. use docker-compose (see [here](https://pastebin.com/raw/pLWtxE3j))
3. failing to start with `read_only: true`

## Context

Thank you, any help would be greatly appriciated.

**Comment by jesec** [comment]
Runtime directory contains databases and temporary folders used by Flood. Flood needs to have **read and write** access to it.

It is `~/.local/share/flood` by default. Previously it is in Flood's source folder (`server/db`). This change is made so system-wide installation to privileged directories like `/usr/bin` can work. Separation of runtime directory from Flood's source directory also increased the security as now more strict file access policies can be applied to Flood's executables to avoid malicious alternation of Flood's control flows.

You may set it via `--rundir`/`-d` command line argument. Or `dbPath` and `tempPath` if static config is used.

**Comment by ojio-san** [comment]
Wow, thank you very much🥇 !

Indeed, you're absolutely right : now it's working with the `~/.local/share/flood` and it wasn't working because I was using `/data` in my volume configuration (from docker-compose.yml). Also, I'm now using `--rundir=/data"` on my `ENTRYPOINT` and it's working 💯
