### ISSUE TITLE
ENOENT Error while trying to setup Transmission

### ISSUE THREAD

**Issue by swanserquack** [jesec/flood#579]
Type: Bug Report

- [x] Try to follow the update procedure described in the README and try again before opening this issue.

## Your Environment

- Version used:
  - Version: 4.7.0
- Environment name and version:
  - Node.js version: v18.7.0
  - npm version: 8.15.1
  - Web browser: Brave v1.41.100
- Operating system and version: Ubuntu Server 22.04
- Torrent client and version: Transmission 3.00 (bb6b5a062e)

## Summary

When trying to get authenticated with Transmission through the rpc using flood, after multiple failed authentication's it shows 'An unknown error occured' and then never lets you try to authenticate again as the service has stopped.

The nodejs logs it states

```
FATAL internal error. Please open an issue.
Uncaught exception: Error: ENOENT: no such file or directory, open '/home/(normal username here)/.local/share/flood/db/F56bLJIdduEDJU9M/history/weekSnapshot.db~'
```

sometimes the nodejs logs show this instead
```
FATAL internal error. Please open an issue.
Uncaught exception: Error: ENOENT: no such file or directory, rename '/home/(normal username here)/.local/share/flood/db/F56bLJIdduEDJU9M/history/weekSnapshot.db~' -> '/home/(normal username here)/.local/share/flood/db/F56bLJIdduEDJU9M/history/weekSnapshot.db'
```

Having a look at the inspect element console shows this (Error happens at the underlined error, everything after that is the effect)
![Screenshot 2022-07-30 190928](https://user-images.githubusercontent.com/75944176/181936235-9db1af27-95e9-4bb8-aeb3-3bd137748123.png)

## Current Behavior

After multiple failed attempts at authentication the flood service shuts down with the error mentioned in the nodejs log.

## Steps to Reproduce

1. Run flood after installing it from nodejs
2. Create a user account on the web interface
3. Set the client to tranmission
4. Fail the authentication multiple times

**Comment by jesec** [comment]
Please try the rolling build.

**Comment by swanserquack** [comment]
Unable to reporduce with the latest rolling build, sorry for wasting your time
