### ISSUE TITLE
"Failed to add 1 torrent" with "unexpected data type" in the RPC response

### ISSUE THREAD

**Issue by dangerman200k** [jesec/flood#580]
Type: Bug Report

- [ ] Try to follow the update procedure described in the README and try again before opening this issue.

## Your Environment

- Version used:
  - 4.7.0 (Docker)
- Environment name and version:
  - Firefox 103.0.1
- Torrent client and version:
  - jesec/rtorrent v0.9.8-r16 binary installed in my own alpine-based image
  - Both containers running under Compose, using a volume to share the RPC socket file, then passing `--rtsocket /var/run/rtorrent/rpc.socket` to Flood.

## Summary

Recently I've become unable to add torrents via the UI. I just get "failed to add 1 torrent". It used to work, and I haven't deliberately changed anything. Opening the dev tools, I can see that `POST /api/torrents/add-files` returned 500 with:
```
{"code":-32602,"message":"invalid parameters: unexpected data type"}
```

rTorrent appears to be running normally, torrents are seeding, Flood can connect to rTorrent and view the existing torrents, the only thing not working is adding. 

Any ideas?

**Comment by dangerman200k** [comment]
I've just deleted the Flood data directory and started from scratch, and everything seems fine now...

**Comment by Tripplesixty** [comment]
This also worked for me, but you need to re-create your account and re-link the underlying client. I suggest creating a backup before blowing away settings.

**Comment by dangerman200k** [comment]
I'm using `--auth none --rtsocket /path`, so no need for that. It's behind an authenticated reverse proxy so I find that easier and it avoids the need for the user info to be stored.
