### ISSUE TITLE
RSS issues

### ISSUE THREAD

**Issue by lukaszraczylo** [jesec/flood#59]
Type: Question

Hi,
First of all - many thanks for picking up this project and continuous hard work on its support!
I've noticed that RSS feeds stop being downloaded / parsed randomly - they're just fine for few minutes right after adding but then produce following:

```
TypeError: l.default.addUrls is not a function
    at /usr/local/lib/node_modules/flood/dist/index.js:2:1262405
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/flood/dist/index.js:2:1262379
```

Wondering if it's just me :)

Flood versions - few latest masters

**Comment by jesec** [comment]
FeedService is the last service that has not been migrated to TypeScript. It is not surprising to me that the service missed out some important changes during refactoring.

The biggest technical problem is the underlying feed component [FeedSub](https://github.com/fent/node-feedsub) does not have types currently. It would involve some extra time and effort to make types and get them merged into DefinitelyTyped.

I will take a look at the issue when I have time and see if I can come up with a solution.

**Comment by lukaszraczylo** [comment]
@jesec thank you so much and again - wonderful job with keeping the project alive!

**Comment by jesec** [comment]
@lukaszraczylo Please verify that the issue is resolved.

**Comment by lukaszraczylo** [comment]
Hi @jesec I can confirm it works 💯 Thank you once again!
