### ISSUE TITLE
413 Request Entity Too Large when trying to add a 1 MB .torrent file

### ISSUE THREAD

**Issue by b1scoito** [jesec/flood#595]
Type: Bug Report

- [x] Try to follow the update procedure described in the README and try again before opening this issue.

## Your Environment

- Version used:
  - Version (stable release): 4.7.0
  - Commit ID (development release) `git --no-pager log -1`: Not development release
- Environment name and version: Docker
  - Node.js version `node --version`: Docker
  - npm version `npm --version`: Docker
  - Web browser `name and version`: Docker
- Operating system and version: Ubuntu Server Linux server 5.15.0-47-generic
- Torrent client and version: jesec/rtorrent from latest jesec/rtorrent-flood release

## Summary

When trying to upload a large file to Flood it just fails to add it.

## Steps to Reproduce

1. Click on add a torrent
2. Drag a torrent that is large
3. Shows up a message saying it failed

**Comment by Sparticuz** [comment]
I'm also getting this error

**Comment by freeone3000** [comment]
Same issue -- Entity limit here needs to be raised to allow for large .torrent files

**Comment by trim21** [comment]
has been fixed, use latest release 4.8.0
