### ISSUE TITLE
Colour ratio

### ISSUE THREAD

**Issue by vain4us** [jesec/flood#60]
Loving flood so far, one of the things that could make it better is having your ratio being coloured, depending on values you set. For example:
0 - 1 , color is dark red
1 - 1.5, color is green
etc

The ruTorrent ratiocolor plugin uses a small script that uses colour fading for the ratio colouring: https://github.com/Gyran/rutorrent-ratiocolor

Would be a cool feature!

**Comment by jesec** [comment]
Related issue: https://github.com/Flood-UI/flood/issues/408

I am a bit worry that this would break color scheme consistency. We also have to exercise additional precautions as some color-background combinations can severely hurt the legibility. 

Is there a potential design? If possible, can you post a screenshot of the proposed/potential color design?

**Comment by vain4us** [comment]
I mean you are kind of right about the legibility, I just checked the default ruTorrent theme with the font colour and some parts are really hard to read:
[Screenshot](https://i.imgur.com/nASf6xO.png)
I guess dark yellow, dark green and red would do fine?

**Comment by vain4us** [comment]
It could use the green that is already used for the download rate statistic for higher ratios. For lower ratios, it could use blue (like the upload ratio). This way the colour scheme doesn't get messed up?

**Comment by jesec** [comment]
I think that would still be a bit confusing.

**Comment by vain4us** [comment]
Since this has already been suggested, I'm closing this issue.

Related: https://github.com/Flood-UI/flood/issues/408
