### ISSUE TITLE
Cannot connect to the client Error

### ISSUE THREAD

**Issue by 20CS003** [jesec/flood#624]
Type: Bug Report

- I try to install Flood on my  local environment using transmission and qbittorrent.

## Your Environment

- Version used:
  -flood version 4.7.0

- Environment name and version:
  - node version : v19.3.0
  - npm version : 9.2.0
  - Web browser : chrome 
- Operating system : Windows 11
- Torrent client and version:  qbittorrent v4.5.0 Transmission 3.00

## Summary

- I try to install Flood on my  local environment using transmission and qbittorrent torrent client but in both i got this same error when I try to run flood . flood is successful started on [http://127.0.0.1:3000/overview](url) and git v Cannot connect to the client dialogue box and also in terminal got this error `GET /api/client/settings 500 7.770 ms - 65` 

## Current Behavior

**Terminal Status**
![209761507-1cf15bee-4bc0-433c-9ffe-8db1192dfd7d (Custom) (1)](https://user-images.githubusercontent.com/90676830/209762131-2576b999-c12c-42be-b5bc-7067677f3c7d.png)

**Transmission Setup**
![209761580-69164da0-4b02-4a00-bdf3-9132e3b9f575 (Custom) (1)](https://user-images.githubusercontent.com/90676830/209762134-647859d9-28c1-484e-bbac-d9ec1a00641d.png)

**Flood localhost**
![209761637-9c4ab83e-2705-4507-b9b6-362896395395 (Custom) (1)](https://user-images.githubusercontent.com/90676830/209762135-be7b1142-35de-44e5-9815-415dac3bbf6d.png)

Please look out at my issue @jesec

**Comment by amitamrutiya2210** [comment]
I got this same error

**Comment by amitamrutiya2210** [comment]
Remove / after transmission/web that work for me mate
Try with this

**Comment by 20CS003** [comment]
I solve my Problem. I am so grateful for your help with this issue. Your expertise and guidance were exactly what I needed. Thank you so much for taking the time to help me out.
