### ISSUE TITLE
Graph not visible in Safari 16.3

### ISSUE THREAD

**Issue by agneevX** [jesec/flood#627]
Type: Bug Report

- [x] Try to follow the update procedure described in the README and try again before opening this issue.

## Your Environment

- Version used:
  - Version (stable release): `master` (`jesec/flood:master`)
  - Commit ID: `7aec1e2`
- Environment name and version:
  - Node.js version `node --version`
  - npm version `npm --version`
  - Web browser `name and version`: Safari 16.3
- Operating system and version: macOS 12.6.3
- Torrent client and version: qBittorrent 4.4.4

## Summary

There isn't a graph visible in Safari 16.3

![image](https://user-images.githubusercontent.com/19761269/215155761-6a232436-85c1-426a-b8f0-bff48f726a77.png)

## Expected Behavior

Graph should be visible.

## Steps to Reproduce

1. Deploy `jesec/flood:master` in a container
2. Open web page in Safari 16.3.

**Comment by ebesirik** [comment]
annoying issue still exist in 16.4 version of Safari

**Comment by Gex2501** [comment]
Same issue here, I just started using flood. Didn't realize this was a safari specific issue until I randomly tried chrome.

**Comment by Gex2501** [comment]
BTW: using Safari 16.5, MacOS 13.4

**Comment by Nevotic** [comment]
Experiencing the same issue with Safari 16.5.

**Comment by agneevX** [comment]
This is not Safari's issue to fix. It'll probably be there in every subsequent version of Safari, so there's no point in spamming here.

**Comment by Gex2501** [comment]
So what's causing the graph to not show?

**Comment by agneevX** [comment]
Safari's WebKit rendering engine has a tendency to break a lot of websites, requiring devs to constantly tweak stuff in its favor, so this isn't exactly surprising.

The dev now works for Meta... given the policies of big tech, they're rarely allowed to contribute to OSS. So I doubt this will ever be fixed, at least in this fork.

Also worth mentioning is that in Safari, the splash screen never stops loading until the page is refreshed.

<img width="463" alt="Screenshot" src="https://github.com/jesec/flood/assets/19761269/a41b6715-08fa-4152-bb4a-d4628822d5e1">

**Comment by agneevX** [comment]
This stands fixed as of builds from the `master` branch.
