### ISSUE TITLE
Flood keeps losing track of rTorrent

### ISSUE THREAD

**Issue by IeuanK** [jesec/flood#632]
Type: Bug Report

- [x] Try to follow the update procedure described in the README and try again before opening this issue.

## Your Environment

I am using the docker image `jesec/flood:master` alongside `TuxMeaLux/alpine-rtorrent` (which is built upon the jesec/rtorrent repository).    
I have a very simple Docker Swarm stack, with a few rTorrent tasks and a Flood task.
My rTorrent instances have a combined 15,750 torrents, but it's split up into four separate instances with no more than 5000 torrents each.  

For some reason, Flood keeps breaking. It will show as running, it shows the login or loading screen, but it will never fetch the torrents.    
The logs show no relevant error messages, and my dev tools also show nothing interesting. It just gets stuck on the loading screen after I log in:  
![image](https://user-images.githubusercontent.com/1075598/215353016-24a78046-0405-41fb-b3e4-1f5bf3297ef4.png)

Dev tools show that it even loads the Flood settings for the authenticated user correctly (I see the last path I saved a torrent to, as well as my column settings). It just never gets past that point.  

Restarting flood using `docker service update -d --force torrents_flood` fixes the issue.

Happy to share logs or a link privately or pop on Discord if more investigation is needed, but I can't really post logs here as there's no relevant info in them and I'm not comfortable publicly sharing the URL to my Flood instance.

**Comment by CircuitCoder** [comment]
Having the same issue with npm installation. It seems that the database files are somehow corrupted. By stopping flood and removing all directory in `~/.local/share/flood/db/` (Keep `users.db` for user configurations), then restarting flood, the issue is fixed.

I kept a copy of the user database files. If it can somehow help with the debugging, I can share it here.

**Comment by trim21** [comment]
I'm using flood with rtorrent and encounter same problem. I can identify there is a bug and memory leak in rtorrent request queue that will cause flood denial of service.

**Comment by trim21** [comment]
We merged a pr to fix some rtorrent request queue bug, can you try the latest master to see if is is fixed?

**Comment by TheLonelyGhost** [comment]
Can confirm, this fixes the exact same issue I saw (described in the issue description).

Using NixOS with NixOS/nixpkgs@cddebdb60de376c1bdb7a4e6ee3d98355453fe56 ([jesec-rtorrent package](https://github.com/NixOS/nixpkgs/tree/cddebdb60de376c1bdb7a4e6ee3d98355453fe56/pkgs/applications/networking/p2p/jesec-rtorrent)), just need to set `services.rtorrent.package = pkgs.jesec-rtorrent`.

**Comment by trim21** [comment]
Looks like this issue has been fixed, feel free to comment if it didn't
