### ISSUE TITLE
How to configure FLOOD HTTPS/SSL connections with signed certificates

### ISSUE THREAD

**Issue by hepf68** [jesec/flood#634]
Type: Documentation Issue

## Summary
I have read all the flood on docker documentation but I didn't find any config info about HTTPS/SSL activation.
Can you explain how to activate https on flood and where we must place the signed digital certificates?

Best Regards,
hepf68

**Comment by trim21** [comment]
Use `--sslcert` and `--sslkey` to specify location of ssl cert and key file path
