### ISSUE TITLE
metrics

### ISSUE THREAD

**Issue by rafipiccolo** [jesec/flood#646]
usually projects provide a /metrics endpoint with useful data for monitoring.
it can be presented in prometheus format.
and it will show nicely in grafana for example.

we could show the number of active / total torrents
the download/upload speed
the total uploaded and downloaded bytes

is anyone interested in this ?

**Comment by trim21** [comment]
Do you have idea about which metrics to export?

**Comment by trim21** [comment]
I have simalier idea, but using a dedicated service would be a better way.
