### ISSUE TITLE
Not showing mount point for merged drives

### ISSUE THREAD

**Issue by sek0n** [jesec/flood#671]
Type: Bug Report

## Your Environment

- Version used:
  - `Docker 0.0.0-master.2b652f8`
- Operating system and version: `Linux`
- Torrent client and version: `qBittorrent 4.5.5`

## Summary

Disk usage not showing mount point for drives that are combined via mergerfs

## Current Behavior

When trying to add '/media' (int1:s1d1:s1d2:s2d1) to the 'Disk Usage' setting, it doesn't show up.

df -h shows:
```
❯ docker exec --user node -it flood df -h
Filesystem                Size      Used Available Use% Mounted on
overlay                 226.7G     34.4G    180.8G  16% /
tmpfs                    64.0M         0     64.0M   0% /dev
shm                      64.0M         0     64.0M   0% /dev/shm
/dev/nvme0n1p2          226.7G     34.4G    180.8G  16% /config
/dev/nvme0n1p2          226.7G     34.4G    180.8G  16% /downloads
int1:s1d1:s1d2:s2d1      12.4T     10.2T      2.2T  82% /media
/dev/nvme0n1p2          226.7G     34.4G    180.8G  16% /home/liam
/dev/nvme0n1p2          226.7G     34.4G    180.8G  16% /etc/resolv.conf
/dev/nvme0n1p2          226.7G     34.4G    180.8G  16% /etc/hostname
/dev/nvme0n1p2          226.7G     34.4G    180.8G  16% /etc/hosts
tmpfs                     7.7G         0      7.7G   0% /proc/asound
tmpfs                     7.7G         0      7.7G   0% /proc/acpi
tmpfs                    64.0M         0     64.0M   0% /proc/kcore
tmpfs                    64.0M         0     64.0M   0% /proc/keys
tmpfs                    64.0M         0     64.0M   0% /proc/timer_list
tmpfs                     7.7G         0      7.7G   0% /sys/firmware
```

What's shown in Flood:
![vivaldi_sfW1ZU5l3V](https://github.com/jesec/flood/assets/12384041/64e8caa2-8905-408e-b633-8b6d0d045945)

## Context

If you don't know what mergerfs is, it basically combines multiple mount points into one, while still being able to access the drives individually from their original mounts.

I have it mounted and visible in docker, as you can see from the df -h. I even added another non-merged drive just to test, and it worked (/test in the screenshot), but nothing seems to work to show the /media mount.

It's added in docker as:
`/home/USER/media:/media`

**Comment by AVCaridi** [comment]
![Screenshot - 2024 05 29 00 34 12](https://github.com/jesec/flood/assets/136209818/0934c8f6-42bf-4e08-81f0-169ec6ffc678)

**Comment by trim21** [comment]
also please provide a full version of output of this command (in text) so I can test it locally

**Comment by AVCaridi** [comment]
> do you have any watchMountPoints config?

I don't believe so.

**Comment by AVCaridi** [comment]
> also please provide a full version of output of this command (in text) so I can test it locally

Run the command in the container or host?

**Comment by trim21** [comment]
are you sure you parse right output here? info of `mergerfs` are splited in to 2 lines?

**Comment by trim21** [comment]
consider use `df -T | tee output.txt` are parse file here

**Comment by AVCaridi** [comment]
Hmm yeah comes up as 1 line on the host but 2 in the container. 

'''sh
/ $ df -T | tee output.txt
tee: output.txt: Permission denied

**Comment by AVCaridi** [comment]
Could it just be the name length?

**Comment by trim21** [comment]
`df -T | tee /config/output.txt` and find file on `/config` (which is the mounted path in the container, find real path in host)

**Comment by trim21** [comment]
> Could it just be the name length?

no. I have logger mount path and they works fine.

**Comment by AVCaridi** [comment]
Same result in the output.txt

**Comment by trim21** [comment]
can you paste file?

**Comment by AVCaridi** [comment]
[output.txt](https://github.com/jesec/flood/files/15473078/output.txt)

**Comment by trim21** [comment]
OK, so I should consider using some API to get info of filesystem instead os parsing text...

**Comment by trim21** [comment]
please try master branch.

**Comment by AVCaridi** [comment]
![Screenshot - 2024 05 29 03 26 05@2x](https://github.com/jesec/flood/assets/136209818/0ed98ddd-46a5-4d73-8aea-69f8dd860350)

**Comment by trim21** [comment]
oops

**Comment by AVCaridi** [comment]
Haha that's all good

**Comment by AVCaridi** [comment]
Host or container?

**Comment by trim21** [comment]
container, always

**Comment by AVCaridi** [comment]
```sh

df: unrecognized option: exclude-type=devtmpfs
BusyBox v1.36.1 (2024-05-21 13:38:37 UTC) multi-call binary.

Usage: df [-PkmhTai] [-B SIZE] [-t TYPE] [FILESYSTEM]...

Print filesystem usage statistics

	-P	POSIX output format
	-k	1024-byte blocks (default)
	-m	1M-byte blocks
	-h	Human readable (e.g. 1K 243M 2G)
	-T	Print filesystem type
	-t TYPE	Print only mounts of this type
	-a	Show all filesystems
	-i	Inodes
	-B SIZE	Blocksize

**Comment by trim21** [comment]
ok, so some old version df doesn't have exclude-type......

**Comment by trim21** [comment]
are you using `jesec/flood`?

**Comment by AVCaridi** [comment]
yeah still using the master

**Comment by trim21** [comment]
should works fine this time.
