### ISSUE TITLE
Connection could not be verified. - qBittorrent v4.5.5 Web UI 

### ISSUE THREAD

**Issue by bulletproof2k** [jesec/flood#682]
It was only possible to create an account in the flood.

I use Windows installer.

**Comment by BychkovSimeon** [comment]
> It was only possible to create an account in the flood.
> 
> I use Windows installer.

Use "http://localhost:8080/#/login" or "http://127.0.0.1:8080/#/login?redirect=%2F" for address

**Comment by julio8a** [comment]
I tried both of the suggested URLs and till getting the same. I'm running it on a Raspberry PI4 using docker. 

I able to access qBittorrent, however, can't login with Flood.

**Comment by SurPaul** [comment]
I have the same. The logs show connection-test 200, but for some reason there is an error in the web interface. I tried connecting via IP and domain.

| Screenshot 1 | Screenshot 2 |
|-|-|
| ![image](https://github.com/jesec/flood/assets/1708881/97508ddc-9bb9-41ea-9ba1-ef94bf90833b) | ![image](https://github.com/jesec/flood/assets/1708881/2d08845b-6927-4c65-9f1c-016b243116f4) |

**Comment by julio8a** [comment]
Hi @SurPaul, I browsed around the repository a bit yesterday and there are a few issues like this one. Some much older. It seems that this repository is not maintained anymore and should probably be deprecated. It's a shame because flood UI is a great interface. 

I switched over to VueTorrent. Works great! Though the UI is not as nice. Best of luck!

**Comment by SurPaul** [comment]
> It seems that this repository is not maintained anymore and should probably be deprecated.

Yes indeed. There have been very few new commits this year.

> I switched over to VueTorrent. Works great! Though the UI is not as nice. Best of luck!

I've been using it for a long time, but after the latest 2.0 update I'm looking for something new 😅

**Comment by vp-en** [comment]
For anyone who still wants to use flood with qBittorrent, check out this [issue / comment](https://github.com/jesec/flood/issues/629#issuecomment-1666908798). I made a working version, building a new version for every commit (like "nightly" releases)

**Comment by engels74** [comment]
> For anyone who still wants to use flood with qBittorrent, check out this [issue / comment](https://github.com/jesec/flood/issues/629#issuecomment-1666908798). I made a working version, building a new version for every commit (like "nightly" releases)

Moved it to https://github.com/engels74/qflood

**Comment by trim21** [comment]
this has been fixed in latest flood 4.8.0

use url without path, for example `https://example.com` instead of `https://example.com/`
