### ISSUE TITLE
Modal bigger than screen on mobile

### ISSUE THREAD

**Issue by whiteout12** [jesec/flood#711]
![Screenshot 2023-12-19 at 09 34 54](https://github.com/jesec/flood/assets/20887517/478309ef-473f-481a-87b1-78eb85827de3)
Type: Bug Report

## Your Environment

Running flood in docker.

- Version used:
  
  - Flood 0.0.0-master.5acf61b

## Summary

When opening a modal in iOS it grows bigger than the screen and dos not fit.
See screenshot

**Comment by trim21** [comment]
@gillesdemey can you take a look？

**Comment by gillesdemey** [comment]
Should be fixed with https://github.com/jesec/flood/pull/713

**Comment by whiteout12** [comment]
This is an issue again.
