### ISSUE TITLE
Modal bigger than screen on mobile

### ISSUE THREAD

**Issue by whiteout12** [jesec/flood#728]
This is an issue again.

_Originally posted by @whiteout12 in https://github.com/jesec/flood/issues/711#issuecomment-2032084900_

**Comment by gillesdemey** [comment]
Hi! Kindly give us some more context or repro steps as I fail to replicate this on `master` with Chrome, Safari and Firefox and there haven't been any commits I could attribute a regression to.

**Comment by whiteout12** [comment]
I think this was misunderstood from my side. See no issue anymore. Closing
