### ISSUE TITLE
Events tooltip not showing

### ISSUE THREAD

**Issue by mirolm** [jesec/flood#73]
Type: Bug Report

- [x] Try to follow the update procedure described in the README and try again before opening this issue.
- [x] Please check the [F.A.Q.](https://github.com/Flood-UI/flood/wiki/F.A.Q.).
- [x] Please check the [Troubleshooting](https://github.com/Flood-UI/flood/wiki/Troubleshooting) wiki section.

## Your Environment

* Version used:
  + Version (stable release) `git --no-pager tag` v3.1.0
  + Commit ID (development release) `git --no-pager log -1` commit ca32dcb49012443e17c03525c2c902943698e497 (HEAD -> master, origin/master, origin/HEAD)
* Environment name and version:
  + Node.js version `node --version` v14.15.0
  + npm version `npm --version` 6.14.8
  + Web browser `name and version` Chromium Version 86.0.4240.111 (Official Build) Arch Linux (64-bit)
* Operating System and version: Debian GNU/Linux 10 (buster) x64

## Summary

Currently the events tooltip somehow gets hidden behind other elements of the flood interface. 

![image](https://user-images.githubusercontent.com/9135358/97907225-9c7c2100-1d4d-11eb-9d10-11bd898de28c.png)

Other tooltips show fine:

![image](https://user-images.githubusercontent.com/9135358/97907789-76a34c00-1d4e-11eb-83a0-602615486398.png)

## Expected Behavior

Events tooltip should show as other tooltips.

## Current Behavior

Events tooltip is broken.

## Steps to Reproduce

1. Start to hover at all elements of flood.
2. Hover the "bell" button with mouse.
3. The tooltip hides behind the other elements of the page.
4.

**Comment by jesec** [comment]
By design, this doesn't show when there is no notification. Nonetheless, indeed, the user experience is not great. It probably should display something like "No notification".

**Comment by jesec** [comment]
With commit 3040304:

![image](https://user-images.githubusercontent.com/11585141/98265925-9f347b80-1fc4-11eb-85a6-b672581677e1.png)

**Comment by mirolm** [comment]
I can confirm tooltip shows fine now.
