### ISSUE TITLE
qBittorrent - how to setup?

### ISSUE THREAD

**Issue by runaroundhome** [jesec/flood#74]
This seems like a silly question, but I can't get it to work.

I've just setup qbittorrent via docker `linuxserver/qbittorrent`, and I can login to the WEB UI fine though the offical one, but when I put in the same user/pass and WEB UI url, I keep getting "Connection could not be verified."

How is it doing it's checking? 
Maybe I can do a seperate test via `curl` or something to check qbittorrent is working correctly.
I assume there are no settings that need to be changed in qbittorent (I've had a look around and don't see any).

I've tested the url `http://qbittorrent:8080/` on another container in the same network and it loads, so I don't think it's a network issue.

Versions:
qBittorrent v4.3.0.1 Web UI (64-bit)
Flood is on the latest build (docker `jesec/flood:master`) 

Any ideas?

![image](https://user-images.githubusercontent.com/16973228/97958022-42dd2a80-1e11-11eb-8071-30cf09ceff1d.png)

Also, maybe unrelated, but I also get these 500 errors, which is strange because if i load http://serverip:3000/api/client/connection-test in the browser I get `{"isConnected":false}`
<img width="795" alt="Screen Shot 2020-11-03 at 8 26 24 PM" src="https://user-images.githubusercontent.com/16973228/97958857-f72b8080-1e12-11eb-8169-18c6f407fa2c.png">

**Comment by jesec** [comment]
Well. What’s `qbittorrent:8080`?

The correct one is probably `127.0.0.1:8080`.

**Comment by runaroundhome** [comment]
qbittorrent is the hostname of the docker container, it resolves into the container ip where my flood UI is running.
I've tried putting in the IP of flood UI, but doesn't help.

**Comment by jesec** [comment]
Flood needs direct file system access and the same file system context as the torrent client. You can not use it to control a remote qBittorrent instance.

**Comment by runaroundhome** [comment]
Hmm, I had flood running with rtorrent in the same setup earlier.

I mean, both flood and qBittorrent are on the same server, same docker, same docker network, and I have mounted the same download dir to flood and qBittorrent, like I did with rtorrent, does flood need file access to other parts of qBittorrent?

**Comment by jesec** [comment]
Try again without the trailing slash.

**Comment by runaroundhome** [comment]
Oooh I'm an idiot, I misconfigured docker. The container qBittorrent was in, was in a different virtual network.

Thanks for all the help! (it works now)
