### ISSUE TITLE
Debs for v4.7.0 have been modified

### ISSUE THREAD

**Issue by OniriCorpe** [jesec/flood#743]
hi!

i'm here to check whether files have been modified voluntarily

our CI has detected a checksum mismatch for your .deb files

```text
2366 WARNING Failed to provision sources : YunoHost was able to download the asset 'main' (https://github.com/jesec/flood/releases/download/v4.7.0/flood-linux-x64.deb) for flood, but the asset doesn't match the expected checksum. This could mean that some temporary network failure happened on your server, OR the asset was somehow changed by the upstream maintainer (or a malicious actor?) and YunoHost packagers need to investigate and perhaps update the app manifest to take this change into account.
    Expected sha256 checksum: d528edc50e2a2a8d60aa1d37e2cdf0353c48f792b7ded4f150a0914931076d3f
    Downloaded sha256 checksum: 9eaf3bbe23354f009952c0146da5b8c349ff6840c9d8867d14697c7ee3392c3a
    Downloaded file size: 22M
```
https://ci-apps.yunohost.org/ci/job/25464

according to github, the two files have been modified at `2024-04-25T20:14:34Z`

![screenshot of the releases, it shows that all the files have been created the "Oct 9, 2021" except the 2 .deb files: "last week"](https://github.com/jesec/flood/assets/6963387/c743fe63-0bf9-4428-95a6-d09210f54de2)

**Comment by trim21** [comment]
emmm strange, this is unexpected

**Comment by OniriCorpe** [comment]
sorry i sent the issue before i finished writing it, i modified it!

**Comment by trim21** [comment]
> sorry i sent the issue before i finished writing it, i modified it!

I get your point， these 2 files should not be modified

**Comment by OniriCorpe** [comment]
umm i thing i get it:
the latest release lacks those 2 deb files, i think there were inadvertently uploaded in the wrong release :/

**Comment by trim21** [comment]
> umm i thing i get it: the latest release lacks those 2 deb files, i think there were inadvertently uploaded in the wrong release :/

yes looks like they are actually 4.8.0

**Comment by trim21** [comment]
I forget to update version number inLinux package files so they build a new package for 4.8.0 as version 4.7.0

**Comment by trim21** [comment]
said story, looks like I can't find these 2 old files.

I'll release a 4.8.1 with new deb files

**Comment by trim21** [comment]
please wait ci complete and close issue.

**Comment by trim21** [comment]
oops they are upload to 4.7.0 release again...

**Comment by trim21** [comment]
fixed in 4.8.2

**Comment by OniriCorpe** [comment]
thank you very much!

**Comment by trim21** [comment]
also deb files in 4.7.0 release are removed, please use file in 4.8.2 release.
