### ISSUE TITLE
Flood changes global speed limits to 0 instead of unlimited

### ISSUE THREAD

**Issue by Sulframus** [jesec/flood#762]
Type: Bug Report

## Your Environment

- Version used:
  - Version v4.8.2
- Environment name and version:
  - Node.js version `v22.1.0`
  - npm version `10.7.0`
  - Web browser `Chrome 126.0.6478.114`
- Operating system and version: Unraid 6.12.10
- Torrent client and version: Transmission 3.00

## Summary

Flood stops the torrent client from downloading and uploading due to incorrect speed limits.

## Expected Behavior

Speeds remain at the set value.

## Current Behavior

I have set download and upload speeds as unlimited, however Flood changes the global upload and download speeds to 0 after a while and all the torrents stall with 0kB/s. After changing the speed to eg. 10 MB/s and back to unlimited, the speeds are unlimited for a short while and then go back to 0.
![image](https://github.com/jesec/flood/assets/50105122/c06ae048-a068-4e72-a189-3a024e00e9bc)

## Steps to Reproduce

Change speed limits to unlimited and wait.

**Comment by LongShengWen** [comment]
I encountered the same problem. When the upload or download is set to unlimited, the upload speed limit on one side will be set to 0 on the other side.

**Comment by trim21** [comment]
please try master branch after https://github.com/jesec/flood/issues/762 is merged
