### ISSUE TITLE
Internal Server ERROR

### ISSUE THREAD

**Issue by WoAnerges** [jesec/flood#798]
Type: Bug Report

E: Failed to fetch https://relay.jesec.workers.dev/?url=https://github.com/jesec/flood/releases/download/v4.7.0/flood-linux-x64.deb  500  Internal Server Error [IP: 172.67.219.38 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by trim21** [comment]
yes， that file was removed by accident

**Comment by WoAnerges** [comment]
is it going to be put back?

**Comment by trim21** [comment]
no

**Comment by trim21** [comment]
also jesec doesn't upload new deb package to apt repo， please install new version from GitHub repo

**Comment by WoAnerges** [comment]
could you please update your manual on how to install from debian? I am following your manual:
https://github.com/jesec/flood/wiki/Install-Flood-on-Debian,-Ubuntu-and-derivatives

Seems like it is outdated then? I am very confused. Could you please provide me with a link that has a manual I could follow, or explain how to install it on debian?

Thank you

**Comment by trim21** [comment]
yes, that should be updated

**Comment by WoAnerges** [comment]
could you in the meantime help me to install it on debian?

**Comment by trim21** [comment]
I think binary is static linked and deb package has no deps, so you can just download deb from github release and run `sudo dpkg -i ....deb`

Or just download binary from github release and put it where you like

**Comment by WoAnerges** [comment]
thank you so much for creating this for the people and for your help today! you have a blessed day :)
