### ISSUE TITLE
Stop and Start torrent doesn't work with qBittorrent 5.0.0

### ISSUE THREAD

**Issue by l4kr** [jesec/flood#800]
Type: Bug Report

## Your Environment

- Version used:
  - Version 4.8.2

- Operating system and version:
  Windows 11
- Torrent client and version:
  qBittorrent 5.0.0

## Expected Behavior

Stop button stops the torrent

## Current Behavior

Doesn't do anything except the page flashes for a split second. Everything else works so far, including adding and removing torrents.

## Possible Solution

Probably a slight change in qBittorrents API

## Steps to Reproduce

1. Have qBittorrent 5.0.0
2. Have Flood 4.8.2
3. Add torrent 
4. Try to stop the torrent

**Comment by SDS1337** [comment]
Same problem. Had to revert to 4.6.7, Seems like it's due to the naming change from Pause/Resume to Start/Stop in 5.0.0. Must've changed the API endpoint as well

**Comment by ndutg** [comment]
Even I am having the same issue.

**Comment by trim21** [comment]
I don't use qb with flood, would anyone like to send a PR?

**Comment by trim21** [comment]
try latest master branch or wait for a release after I merge new translation

**Comment by SDS1337** [comment]
Slightly unrelated, it seems now on stopping a torrent the visible color of state remains green (instead of grey)
