### ISSUE TITLE
Feature Request: qBittorrent categories support?

### ISSUE THREAD

**Issue by runaroundhome** [jesec/flood#81]
Type: Feature Request

## Summary
You've done amazing work on this since forking it (Thank you!!), so hate to ask for anything, but any plans on adding the categories for qBittorrent?

## Idea of implementation
Not sure why qbt even has both tags and cats, I'd be happy with just an option to link cats to tags in flood, and ignore tags from qbt, but that's kinda a hack way about it.
I only ask about cats support because sonarr/radarr etc uses cats, and sometimes I manually add torrents and need to assign the sonarr category.

Not sure how easy it is to add a new filtering option.

**Comment by jesec** [comment]
Categories in qBittorrent are exclusive. One torrent can only have one category. It is duplicative to have both tag and category. Other clients don't support categories, either. 

As such, I don't think this feature can be implemented.

**Comment by jesec** [comment]
The best way to solve the problem is to add Flood support to Sonarr/Radarr. It should be quite straightforward with the documented APIs of Flood. However, it does demand some experience in C#.

**Comment by runaroundhome** [comment]
Hmmm, didn't think about going that route, will look into creating a DownloadClient for flood then. I've not used C# before, but how hard could it be..
