### ISSUE TITLE
Flood unable to start/stop torrents on qBittorrent

### ISSUE THREAD

**Issue by 825i** [jesec/flood#818]
Type: Bug Report

## Your Environment

Unraid Docker Image

- Version used: **Flood 0.0.0-master.3cffd50**
- Operating system and version: **Unraid 6.12.13**
- Torrent client and version: **qBittorrent v5.0.1**

## Summary

Flood runs and works fine. I can even add or remove torrents and they download or are removed.
However, as soon as I try to **start or stop** a torrent. It will kill the connection.

Check this animation:
https://github.com/user-attachments/assets/ea3cb709-1bfe-4151-a6d1-4be29d29e1e3

## Expected Behavior

I should be able to start/stop/etc. torrents from Flood

## Current Behavior

Flood will crash for a split second to the reconnection window before connecting automatically again.
Nothing will happen to the torrent. The action is not recorded.

## Steps to reproduce

1. Add a torrent via qBittorrent or Flood
2. Right click to start or stop the torrent
3. Flood crashes for a moment to the reconnection window
4. Nothing happens to the torrent

**Comment by LXGaming** [comment]
You're running an old version of Flood https://github.com/jesec/flood/commit/3cffd50a16b2e3fdac94928169c4754d6a6144f6 which doesn't support qBittorrent 5, you'll need to update Flood.

I'm not familiar with Unraid, I'm assuming you need to update the "App" or contact the author to update it, there is an official docker image https://hub.docker.com/r/jesec/flood if that helps.

Related Issue: https://github.com/jesec/flood/issues/800

**Comment by 825i** [comment]
Thank you so much. Updating to v4.8.4 fixed the problem.

I just swapped from: `fico/flood` to `jesec/flood`
