### ISSUE TITLE
"No Torrents To Display" when connected to QBittorrent on macOS

### ISSUE THREAD

**Issue by geepy123456790123** [jesec/flood#824]
Type: Bug Report

I'm able to log in and connect to qBittorrent 5.0.0 on macOs, but when I get into Flood, all I see is "No Torrents To Display"

Your Environment

- Version used: 4.8.4
- Environment name and version:
  - Node.js version v23.2.0
  - npm version 10.9.0
  - Web browser Chrome 130.0.6723.117
- Operating system and version: macOS Sonoma 14.5
- Torrent client and version: qBittorrent 5.0.0

## Summary

I'm able to log in and connect to qBittorrent 5.0.0, but when I get into Flood, all I see is "No Torrents To Display". I've tried restarting QBittorrent, downgrading QBittorrent, reinstalling Flood, nothing helps.

## Expected Behavior

Should show currently active torrents, upload/download rates, _anything_

## Current Behavior

No torrents, download/upload rates, or torrent counts show at all.

**Comment by trim21** [comment]
can you try edge docker image on master branch?

**Comment by trim21** [comment]
this should already be fixed, reply to this if it's not actually fixed and I'll re-open this issue.
