### ISSUE TITLE
Added 'Last Transfer' date in torrents details: list, modal, UI column settings

### ISSUE THREAD

**Issue by gboudreau** [jesec/flood#9]
Type: Discussion

## Discussion

I couldn't send you a PR, because your repo is disconnected from the original one, but maybe you're interested in this:
https://github.com/Flood-UI/flood/pull/882

Cheers.

**Comment by jesec** [comment]
It looks good. However, it could be problematic to support a feature that is not present in vanilla rTorrent and requires user to change their rTorrent configurations. Some users might complain that "Last transfer" is not working if they are not aware of the setup procedures.

**Comment by gboudreau** [comment]
True; would be better to make it user-selectable in the settings, and add a link to the documentation next to it.
If other users are interested, at least now that can see it could work, and might upvote it, which could give us an idea on if it's worth the effort to continue working in that direction.

**Comment by jesec** [comment]
I think you can probably try to send necessary commands to rTorrent from Flood. Another option is to incorporate the feature into rTorrent.
